var dw={};dw.version={major:0,minor:1};dw.error=function(d){typeof console=="undefined"?alert(d):console.error(d)};dw.listen=function(d,a,b){b=dw.listener(b);return d.addEventListener?d.addEventListener(a,b,false):d.attachEvent("on"+a,b)};dw.listener=function(d){return d.$listener||(d.$listener=function(a){try{dw.event=a;return d.call(this,a)}finally{delete dw.event}})};dw.jq=function(d){return jQuery(document.createElement(d))};
dw.add_select_option=function(d,a,b){if(arguments.length<3)b=a;var c=document.createElement("option");c.value=b;c.text=a;d[0].options.add(c)};dw.progress_call=function(d){var_args=Array.prototype.slice.call(arguments).slice(2);d.apply(var_args[0],var_args);return this};dw.log=function(d){d.dt=new Date;var a=d.table;d.table=[];JSON.stringify(d);d.table=a};
dw.merge_sort=function(d,a){a=a||dw.merge_sort.stringCompare;if(d.length<2)return d;var b=Math.ceil(d.length/2);return dw.merge_sort.merge(dw.merge_sort(d.slice(0,b),a),dw.merge_sort(d.slice(b),a),a)};dw.merge_sort.merge=function(d,a,b){for(var c=[];d.length>0&&a.length>0;)b(d[0],a[0])<0?c.push(d.shift()):c.push(a.shift());for(;d.length>0;)c.push(d.shift());for(;a.length>0;)c.push(a.shift());return c};dw.merge_sort.stringCompare=function(d,a){d=""+d;a=""+a;return dw.merge_sort.compare(d,a)};
dw.merge_sort.compare=function(d,a){return d==a?0:d<a?-1:1};dw.merge_sort.numberCompare=function(d,a){if(d===undefined&&a===undefined)return 0;if(d===undefined)return-1;if(a===undefined)return 1;leftNo=Number(d);rightNo=Number(a);if(isNaN(leftNo)&&isNaN(rightNo))return dw.merge_sort.compare(d,a);else if(isNaN(leftNo))return-1;else if(isNaN(rightNo))return 1;return dw.merge_sort.compare(leftNo,rightNo)};
dw.merge_sort.dateCompare=function(d,a){leftNo=Number(d);rightNo=Number(a);if(isNaN(leftNo)&&isNaN(rightNo))return dw.merge_sort.compare(d,a);else if(isNaN(leftNo))return rightNo;else if(isNaN(rightNo))return leftNo;return dw.merge_sort.compare(leftNo,rightNo)};
dw.merge_sort.getDateComparison=function(){var d=function(a){return Date.parse(a)};return function(a,b){leftNo=d(a);rightNo=d(b);if(leftNo&&rightNo){if(leftNo<rightNo)return-1;if(rightNo>leftNo)return 1;return 0}else if(leftNo)return-1;else if(rightNo)return 1;return dw.merge_sort.compare(leftNo,rightNo)}};dw.display_name=function(d){return d};dw.JSON={};
(function(){function d(i){return i<10?"0"+i:i}function a(i){e.lastIndex=0;return e.test(i)?'"'+i.replace(e,function(k){var m=h[k];return typeof m==="string"?m:"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+i+'"'}function b(i,k){var m,n,u=f,x,y=k[i];if(y&&typeof y==="object"&&typeof y.toJSON==="function")y=y.toJSON(i);if(typeof j==="function")y=j.call(k,i,y);switch(typeof y){case "string":return a(y);case "number":return isFinite(y)?String(y):"null";case "boolean":case "null":return String(y);
case "object":if(!y)return"null";f+=g;x=[];if(Object.prototype.toString.apply(y)==="[object Array]"){n=y.length;for(i=0;i<n;i+=1)x[i]=b(i,y)||"null";k=x.length===0?"[]":f?"[\n"+f+x.join(",\n"+f)+"\n"+u+"]":"["+x.join(",")+"]";f=u;return k}if(j&&typeof j==="object"){n=j.length;for(i=0;i<n;i+=1){m=j[i];if(typeof m==="string")if(k=b(m,y))x.push(a(m)+(f?": ":":")+k)}}else for(m in y)if(Object.hasOwnProperty.call(y,m))if(k=b(m,y))x.push(a(m)+(f?": ":":")+k);k=x.length===0?"{}":f?"{\n"+f+x.join(",\n"+f)+
"\n"+u+"}":"{"+x.join(",")+"}";f=u;return k}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var c=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,g,h={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;if(typeof dw.JSON.stringify!=="function")dw.JSON.stringify=function(i,k,m){var n;g=f="";if(typeof m==="number")for(n=0;n<m;n+=1)g+=" ";else if(typeof m==="string")g=m;if((j=k)&&typeof k!=="function"&&(typeof k!=="object"||typeof k.length!=="number"))throw new Error("dw.JSON.stringify");
return b("",{"":i})};if(typeof dw.JSON.parse!=="function")dw.JSON.parse=function(i,k){function m(n,u){var x,y,B=n[u];if(B&&typeof B==="object")for(x in B)if(Object.hasOwnProperty.call(B,x)){y=m(B,x);if(y!==undefined)B[x]=y;else delete B[x]}return k.call(n,u,B)}i=String(i);c.lastIndex=0;if(c.test(i))i=i.replace(c,function(n){return"\\u"+("0000"+n.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(i.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){i=eval("("+i+")");return typeof k==="function"?m({"":i},""):i}throw new SyntaxError("dw.JSON.parse");}})();
dw.wrangle=function(){var d=[];d.apply=function(a){if(typeOf(a)!="array")a=[a];d.forEach(function(b){if(b.active()||b.invalid()){var c=b.check_validity(a);if(c.valid){b.sample_apply(a);dw.infer_type_transforms(a[0]).forEach(function(e){e.sample_apply([a[0]])});b.validate()}else b.invalidate(c.errors)}});dw.summary.clear_cache();return d};d.add=function(a){d.push(a);return d};return d};dw=dw||{};
dw.regex=function(){var d={},a=function(f){return[new RegExp(f),/\d+/]},b=function(f){var g=[new RegExp(f),/[a-zA-Z]+/];if(f.toLowerCase()===f)g.push(/[a-z]+/);else f.toUpperCase()===f&&g.push(/[A-Z]+/);return g},c=function(f){var g;if(["|"].indexOf(f)!=-1)f="\\"+f;try{g=new RegExp(f)}catch(h){g=new RegExp("\\"+f)}return[g]};d.candidates=function(f){if(f.length){var g=d.parse(f[0].text,f[0].start,f[0].end),h=f.slice(0),j;f=(g.on||[]).map(function(m){return{on:m}});var i=g.before,k=g.after;g=i===undefined||
i.length===0?k.map(function(m){return{after:m,on:/.*/}}):k===undefined||k.length===0?i.map(function(m){return{before:m,on:/.*/}}):(i||[]).reduce(function(m,n){return m.concat((k||[]).map(function(u){return{before:n,after:u,on:/.*/}}))},[]);g=f.concat(g);if(h.length===0)return g;return g=g.filter(function(m){return h.filter(function(n){j=dw.regex.match(n.text,m);return j.length<2||j[1].start!=n.start||j[1].end!=n.end}).length===0})}return[]};var e=function(f){f=f.map(function(g){return g.toString().replace(/^\/|\/$/g,
"")}).join("");return new RegExp(f)};d.parse=function(f,g,h,j){f=""+f;var i=/([a-zA-Z]+)|([0-9]+)|([^a-zA-Z0-9])/g;f=(f.substring(0,g).match(i)||[]).concat(f.substring(g,h).match(i)||[]).concat(f.substring(h).match(i)||[]);j=j||{};var k,m,n,u=0;i=j.matchAfter||3;var x=j.matchBefore||3;f=f.filter(function(B){return B!=null});j=f.map(function(B,F){k=B.charCodeAt(0);if(g>=u&&g<u+B.length)m=F;if(h>u&&h<=u+B.length)n=F;u+=B.length;return k>64&&k<91||k>96&&k<123?b(B):k>47&&k<58?a(B):c(B)});if(m===undefined)m=
f.length-1;if(n===undefined)n=f.length-1;f=j.slice(m,n+1).reduce(function(B,F){var v=[];B.forEach(function(E){F.forEach(function(s){v.push(E.concat(s))})});return v},[[]]);var y=function(B,F){var v=[];if(B.length){B.forEach(function(E){F.forEach(function(s){v.push(E.concat(s))})});return B.concat(v)}else return F.map(function(E){return[E]})};i=j.slice(Math.max(m-i-1,0),m).reverse().reduce(y,[]);j=j.slice(n+1,Math.min(n+x+1,j.length)).reduce(y,[]);return{on:f.map(e),after:(i||[]).map(function(B){return e(B.reverse())}),
before:(j||[]).map(function(B){return e(B)})}};return d};dw.regex.record=function(d,a,b,c,e,f){return{text:d,start:a,end:b,col:c,row:e,table:f}};
dw.regex.friendly_description=function(d){d=d.toString().replace(/^\/|\/$/g,"");d=d.replace(/\n/g,"newline");d=d.replace(/ /g," ");d=d.replace(/\t/g,"tab");d=d.replace(/\(?(\[0\-9\]|\\d)\+\)?/g," any number ");d=d.replace(/\(?(\[a\-z\A\-Z\]|\[A\-Z\a\-\z\])\+\)?/g," any word ");d=d.replace(/\(?(\[a\-z\])\+\)?/g," any lowercase word ");d=d.replace(/\(?(\[A\-Z\])\+\)?/g," any uppercase word ");d=d.replace(/\$$/,"{end}");d=d.replace(/^\^/,"{begin}");d=d.replace("\\","");if(d==="newline")return d;return"'"+
d+"'"};dw.regex.description_length=function(d){if(!d)return 0;d=d.toString().replace(/^\/|\/$/g,"");d=d.replace(/\\n/g,"n");d=d.replace(/ /g," ");d=d.replace(/\t/g,"t");d=d.replace(/\(?(\[0\-9\]|\\d)\+\)?/g,"n");d=d.replace(/\(?(\[A\-Z\])\+\)?/g," w");d=d.replace(/\(?(\[a\-z\])\+\)?/g,"w");d=d.replace(/\(?(\[a\-z\A\-Z\]|\[A\-Z\a\-\z\])\+\)?/g,"w");d=d.replace(/\$$/,"e");d=d.replace(/^\^/,"b");d=d.replace("\\","");return d.match(/([a-zA-Z]+)|([0-9]+)|([^a-zA-Z0-9])/g).length+1};
dw.regex.match=function(d,a){if(!d)return"";var b=a.max_splits;if(b===undefined)b=1;var c={start:0,end:d.length,value:d};d=[];var e=0,f=Number(a.which);if(isNaN(f))f=1;for(;b<=0||e<b*f;){var g=dw.regex.matchOnce(c.value,a);if(g.length>1){c=g[2];d.push(g[0]);d.push(g[1])}else break;e++;if(e>1E3)break}d.push(c);a=0;b=[];c="";for(e=0;e<d.length;++e){if(e%2===1){a++;if(a===f){b.push({value:c,start:0,end:c.length});b.push({start:c.length,end:c.length+d[e].value.length,value:d[e].value});a=0;c="";continue}}c+=
d[e].value}b.push({start:0,end:c.length,value:c});return b};
dw.regex.matchOnce=function(d,a){var b=a.positions,c=[];if(b&&b.length)if(b.length==2){if(d.length>=b[1]){var e=b[0];b=b[1];c.push({start:0,end:e,value:d.substr(0,e)});c.push({start:e,end:b,value:d.substr(e,b-e)});c.push({start:b,end:d.length,value:d.substr(b)});return c}return[{start:0,end:d.length,value:d}]}e=a.before;b=a.after;for(var f=a.on,g=a.ignore_between,h=d,j=0,i=0;h.length;){var k=h,m=0;i=j;if(g)if(a=h.match(g)){k=k.substr(0,a.index);j+=a.index+a[0].length;h=h.substr(a.index+a[0].length)}else h=
"";else h="";if(b)if(a=k.match(b)){m=a.index+a[0].length;k=k.substr(m)}else continue;if(e)if(a=k.match(e))k=k.substr(0,a.index);else continue;if(a=k.match(f)){e=i+m+a.index;b=e+a[0].length;c.push({start:0,end:e,value:d.substr(0,e)});c.push({start:e,end:b,value:d.substr(e,b-e)});c.push({start:b,end:d.length,value:d.substr(b)});return c}}return[{start:0,end:d.length,value:d}]};
dw.copy=function(d){var a=dw.map(d);a.well_defined=function(){return a._column.length===1};a.transform=function(b){return b};a.description=function(){return["Copy",dw.column_clause(a,a._column,"column")]};a.name=dw.transform.COPY;return a};
dw.cut=function(d){var a=dw.textPattern(d);a._drop=false;a._update=true;a.transform=function(b){if(b[0]===undefined)return[];if(a._positions&&a._positions.length){var c=""+b[0],e=a._positions;b=e[0];e=e[1]||e[0];var f=[];f.push(c.substring(0,b)+c.substring(e));f.stats=[{splits:[{start:b,end:e}]}];return f}else{e=[];for(f=0;f<b.length;++f){c=b[f];c=dw.regex.match(c,{which:a._which,max_splits:a._max,before:a._before,after:a._after,on:a._on,ignore_between:a._ignore_between});var g=[];g.stats=[];for(var h=
0;h<c.length;++h)h%2==0?g.push(c[h].value):g.stats.push({splits:[{start:c[h].start,end:c[h].end}]});e.push(g.join(""));if(!f)e.stats=g.stats}return e}};a.description=function(){var b=[a._column&&a._column.length?"Cut from":"Cut",dw.column_clause(a,a._column,"column")];regex=a.match_description();return b=b.concat(regex)};a.name=dw.transform.CUT;return a};
dw.drop=function(d){var a=dw.transform(d);a._drop=true;dv.ivar(a,[]);a.description=function(){return["Drop",dw.column_clause(a,a._column,"column",{editor_class:"droppedColumn"})]};a.apply=function(b){var c=a.getTable(b);b=a.columns(c);a._drop&&b.forEach(function(e){c.removeColumn(e.name)});return{droppedCols:b}};a.name=dw.transform.DROP;return a};
dw.extract=function(d){var a=dw.textPattern(d);a.transform=function(b){if(b[0]===undefined)return[];if(a._positions&&a._positions.length){b=""+b[0];var c=a._positions,e=c[0];c=c[1]||c[0];var f=[];if(c<=b.length){f.push(b.substring(e,c));f.stats=[{splits:[{start:e,end:c}]}]}return f}else{b=dw.regex.match(b[0],{which:a._which,max_extracts:a._max,before:a._before,after:a._after,on:a._on,ignore_between:a._ignore_between});e=[];e.stats=[];for(c=0;c<b.length;++c)if(c%2==1){e.push(b[c].value);e.stats.push({splits:[{start:b[c].start,
end:b[c].end}]})}return e}};a.description=function(){var b=["Extract from",dw.column_clause(a,a._column,"column",{editor_class:"none"})];regex=a.match_description({editor_class:"extract"});return b=b.concat(regex)};a.name=dw.transform.EXTRACT;return a};dw.LEFT="left";dw.UP="up";dw.DOWN="down";dw.RIGHT="right";dw.COPY="copy";dw.INTERPOLATE="interpolate";
dw.fill=function(d){var a=dw.transform(d);dv.ivar(a,[{name:"direction",initial:dw.DOWN},{name:"method",initial:dw.COPY},{name:"row",initial:undefined}]);a.description_length=function(){if(a._row)return a._row.description_length();return 0};a.description=function(){return["Fill",dw.column_clause(a,a._column,"column",{all_columns:true}),dw.row_clause(a,a._row,"row",{editor_class:"updatedColumn"}),"with","values from",dw.select_clause(a,{select_options:{right:"the left",left:"the right",up:"below",down:"above"},
param:"direction"})]};a.apply=function(b){b=a.getTable(b);var c=a.columns(b),e=b.rows(),f=a._row||dw.row(),g=a._direction;if(a._method===dw.COPY){var h,j;if(g===dw.DOWN)for(var i=0;i<c.length;++i){g=c[i];j=undefined;for(var k=0;k<e;++k){h=g[k];if(h===undefined||h===""){if(f.test(b,k))g[k]=j}else j=h}}else if(g===dw.RIGHT)for(k=0;k<e;++k){if(f.test(b,k)){j=undefined;for(i=0;i<c.length;++i){g=c[i];h=g[k];if(h===undefined||h==="")g[k]=j;else j=h}}}else if(g===dw.LEFT)for(k=0;k<e;++k){if(f.test(b,k)){j=
undefined;for(i=c.length-1;i>=0;--i){g=c[i];h=g[k];if(h===undefined||h==="")g[k]=j;else j=h}}}else if(g===dw.UP)for(i=0;i<c.length;++i){g=c[i];j=undefined;for(k=e-1;k>=0;--k){h=g[k];if(h===undefined||h===""){if(f.test(b,k))g[k]=j}else j=h}}}return{updatedCols:c}};a.horizontal=function(){return a._direction===dw.LEFT||a._direction===dw.RIGHT};a.well_defined=function(b){b=a.columns(b);a.horizontal();if(a._row){var c=a._row.conditions();if(c.length===1)if(c[0].name!==dw.row.INDEX)if(c[0].name===dw.row.EMPTY)return false}if(a.horizontal()){if(b.length===
1)return false;var e=false,f=false;if(a._row===undefined){if(a._direction===dw.LEFT)for(var g=0;g<b.length;++g){c=b[g];if(dw.summary(c).missing.length===0){if(f){e=true;break}}else f=true}else if(a._direction===dw.RIGHT)for(g=b.length-1;g>=0;--g){c=b[g];if(dw.summary(c).missing.length===0){if(f){e=true;break}}else f=true}if(!e)return false}}else if(b.filter(function(h){return dw.summary(h).missing.length===0}).length)return false;return true};a.enums=function(){return["direction"]};a.name=dw.transform.FILL;
return a};
dw.filter=function(d){var a=dw.transform();d=dw.row(d);dv.ivar(a,[{name:"row",initial:d}]);a.description=function(){return["Delete",dw.row_clause(a,a._row,"row")]};a.description_length=function(){if(a._row)return a._row.description_length();return 0};a.apply=function(b,c){c=c||{};b=a.getTable(b);var e=b.cols(),f=b.rows(),g=a._row,h=b.slice(0,0),j=[];f=c.end_row||f;for(var i=c.start_row||0;i<f;++i)if(g.test(b,i))j.push(i);else for(c=0;c<e;++c){col=h[c];col.push(b[c][i])}e=b.cols();g=b.names();f=b.types();
for(c=0;c<e;++c)b.removeColumn(0);for(c=0;c<e;++c)b.addColumn(g[c],h[c],f[c]);return{effectedRows:j}};a.valid_columns=function(b){if(a._row)return a._row.valid_columns(b);return{valid:true}};a.well_defined=function(){return a._row.conditions().length};a.name=dw.transform.FILTER;return a};
dw.fold=function(d){var a=dw.transform(d);dv.ivara(a,{name:"keys",initial:[-1]});a.description=function(){return["Fold",dw.column_clause(a,a._column,"column")," using ",dw.key_clause(a,a._keys.map(function(b){return b===-1?"header":b}),"keys",{editor_class:"fold",clean_val:function(b){return Number(b)}}),a._keys.length===1?"as a key":" as keys "]};a.apply=function(b,c){c=c||{};var e=a.getTable(b);b=a.columns(e);var f=b.map(function(v){return v.name}),g=e.rows(),h=0,j,i=c.start_row||0;c=c.end_row||
g;c=Math.min(c,g);g=b.map(function(v){return a._keys.reduce(function(E,s){s===-1?E.push(dw.display_name(v.name)):E.push(v[s]);return E},[])});var k=dv.range(g[0].length).map(function(){var v=[];v.name="fold";v.type=dv.type.nominal;return v}),m=[];m.name="value";m.type=dv.type.nominal;var n,u=false,x=e.filter(function(v){if(f.indexOf(v.name)===-1)return true;else u||(n=v);u=true;return false}).map(function(v){var E=[];E.name=v.name;E.type=v.type;return E});for(i=i;i<c;++i)if(a._keys.indexOf(i)===-1)for(var y=
0;y<b.length;++y){for(var B=0;B<x.length;++B){j=x[B];j[h]=e[j.name][i]}for(j=0;j<k.length;++j)k[j][h]=g[y][j];m[h]=b[y][i];++h}for(var F=n?n.index():0;e.cols();)e.removeColumn(0);x.forEach(function(v){e.addColumn(v.name,v,v.type)});k.concat([m]).forEach(function(v,E){e.addColumn(v.name,v,v.type,v.wrangler_type,v.wrangler_role,{index:F+E})});return{keyCols:k,valueCols:[m],toValueCols:b,keyRows:a._keys}};a.well_defined=function(){return true};a.name=dw.transform.FOLD;return a};
dw.map=function(d){var a=dw.transform(d);dv.ivar(a,[{name:"result",initial:dw.COLUMN},{name:"update",initial:false},{name:"insert_position",initial:dw.INSERT_RIGHT},{name:"row",initial:undefined}]);a.apply=function(b,c){c=c||{};var e=a.getTable(b),f=a.columns(e),g=e.rows(),h;b=[];var j=c.start_row||0;c=c.end_row||g;g=a._row;var i=dw.transform.tableUpdate(a,e,f);for(j=j;j<c;++j)if(!g||g.test(e,j)){h=[];for(var k=0;k<f.length;++k)h.push(f[k][j]);h=a.transform(h);b.push(h.stats);h=i.update(j,h);if(h>
1E3)break}i.finish();e=i.stats();e.valueStats=b;return e};return a};dw.merge=function(d){var a=dw.map(d);dv.ivar(a,[{name:"glue",initial:""}]);a.transform=function(b){var c=a.glue();return[b.filter(function(e){return e!=undefined}).join(c)]};a.description=function(){return["Merge",dw.column_clause(a,a._column,"column")," with glue ",dw.input_clause(a,"glue")]};a.well_defined=function(){return a._column.length>1};a.name=dw.transform.MERGE;return a};
dw.reduce=function(d){var a=dw.transform(d);dv.ivara(a,[{name:"measures",initial:[]}]);a.description=function(){return["reduce",dw.column_clause(a,a._column)," with aggregates ",dw.column_clause(a,a._measures)]};a.apply=function(b){b=a.getTable(b);b.slice(0,b.rows(),{compress:true});var c=a.columns(b).map(function(e){return e.name});b.rows();b.query({dims:c,vals:a._measures.map(function(e){return dv.first(e)})});b=dv.table([]);return{}};a.name=dw.transform.UNFOLD;return a};
dw.row=function(d){var a=dw.transform();dv.ivara(a,[{name:"conditions",initial:d||[]}]);a.description_length=function(){if(a._conditions.length===0)return 0;if(a._conditions.length===1)switch(a._conditions[0].name){case dw.row.INDEX:return 1;case dw.row.EMPTY:return 2;default:break}return 3};a.description=function(){if(a._conditions.length===1)switch(a._conditions[0].name){case dw.row.INDEX:case dw.row.EMPTY:return a._conditions[0].description({simple:true});default:break}return[" rows where "+a._conditions.map(function(b){return b.description()}).join(" and ")]};
a.formula=function(){return a._conditions.map(function(b){return b.description()}).join(" and ")};a.valid_columns=function(b){for(var c=a._conditions,e,f=0;f<c.length;++f){e=c[f];e=e.valid_columns(b);if(!e.valid)return e}return{valid:true}};a.test=function(b,c){for(var e=a._conditions,f,g=0;g<e.length;++g){f=e[g];if(!f.test(b,c))return 0}return 1};a.name=dw.transform.ROW;return a};
dw.row.fromFormula=function(d){if(d==="")return dw.row([]);d=d.split(/ & /g);d=d.map(function(a){if(a==="row is empty")return dw.empty();if(e=a.indexOf("index in (")!=-1){var b=a.substring(e+9,a.length-1);b=b.split(/,/g).map(function(f){return Number(f)-1});return dw.rowIndex(b)}var c=a.match(/\=|<\=|>\=|!=|is null|is not|matches role|matches type|like/);b=c[0];var e=c.index;c=a.substr(0,e).replace(/^ */,"").replace(/ *$/,"");a=a.substr(e+b.length).replace(/^ * /,"").replace(/ *$/,"");switch(a){case "a number":a=
dw.number();break;case "a date":a=dw.date();break;case "a string":a=dw.string();break;case "a integer":a=dw.integer();break;default:a=a[0]==="'"?a.substring(1,a.length-1):Number(a)}switch(b){case "=":b=dw.eq(c,a,true);break;case "<":b=dw.lt(c,a,true);break;case "<=":b=dw.le(c,a,true);break;case ">":b=dw.gt(c,a,true);break;case ">=":b=dw.ge(c,a,true);break;case "!=":b=dw.ne(c,a,true);break;case "is null":b=dw.is_null(c);break;case "matches role":b=dw.matches_role(c);break;case "is not":b=dw.matches_type(c,
a);break;case "matches type":b=dw.matches_type(c);break;case "~":b=dw.like(c,a,true);break;default:throw"Invalid row predicates";}return b});return dw.row(d)};dw.row.INDEX="rowIndex";dw.row.EMPTY="empty";dw.row.IS_NULL="is_null";dw.row.IS_VALID="is_valid";dw.row.MATCHES_ROLE="is_role";dw.row.MATCHES_TYPE="is_type";dw.row.STARTS_WITH="starts_with";dw.row.LIKE="like";dw.row.EQUALS="eq";dw.row.CONTAINS="contains";
dw.rowIndex=function(d){var a=dw.transform();dv.ivara(a,[{name:"indices",initial:d||[]}]);a.test=function(b,c){return a._indices.indexOf(c)!=-1};a.description=function(b){b=b||{};d=a._indices;return b.simple?(d.length===1?d[0]===-1?"":"row ":"rows ")+d.map(function(c){return c===-1?"header":c+1}).join(","):"index in ("+d.map(function(c){return c+1}).join(",")+")"};a.valid_columns=function(){return{valid:true}};a.name=dw.row.INDEX;return a};
dw.vcompare=function(d,a){var b=dw.transform();dv.ivar(b,[{name:"lcol",initial:d},{name:"value",initial:a}]);b.test=function(c,e){return b.compare(c[b._lcol][e],a)};b.description=function(){return dw.display_name(b._lcol)+" "+b._op_str+" '"+b._value+"'"};b.valid_columns=function(c){if(c[0][d])return{valid:true};return{valid:false,errors:["Invalid left hand side"]}};return b};
dw.ccompare=function(d,a){var b=dw.transform();dv.ivar(b,[{name:"lcol",initial:d},{name:"rcol",initial:a}]);b.test=function(c,e){return b.compare(c[d][e],c[a][e])};b.description=function(){return dw.display_name(b._lcol)+" "+b._op_str+" "+b._rcol};b.valid_columns=function(c){if(c[0][d]&&c[0][a])return{valid:true};return{valid:false,errors:["Invalid comparison"]}};return b};
dw.compare=function(d,a,b){var c=b?dw.vcompare(d,a):dw.ccompare(d,a);c.default_transform=function(){return dw[c.name](d,a,b)};return c};dw.eq=function(d,a,b){d=dw.compare(d,a,b);d._op_str="=";d.compare=function(c,e){return c===e};d.name=dw.row.EQUALS;return d};dw.starts_with=function(d,a,b){d=dw.compare(d,a,b);d._op_str="starts with";d.compare=function(c,e){c=""+c;e=""+e;return c.indexOf(e)==0};d.name=dw.row.STARTS_WITH;return d};
dw.like=function(d,a){d=dw.compare(d,a,true);d._op_str="~";d.compare=function(b,c){b=""+b;c=""+c;return b.match(c)!=null};d.name=dw.row.LIKE;return d};dw.contains=function(d,a,b){d=dw.compare(d,a,b);d._op_str="contains";d.compare=function(c,e){c=""+c;e=""+e;return c.indexOf(e)!=-1};d.name=dw.row.CONTAINS;return d};
dw.is_null=function(d,a){var b=dw.compare(d,a,true);b._op_str="is null";b.compare=function(c){return dw.is_missing(c)};b.description=function(){return dw.display_name(b._lcol)+" "+b._op_str};b.name=dw.row.IS_NULL;return b};
dw.matches_role=function(d){var a=dw.transform();dv.ivar(a,[{name:"lcol",initial:d}]);a.test=function(b,c){return!b[d].wrangler_role.parse(b[d][c])};a.description=function(){return dw.display_name(a._lcol)+" does not match role"};a.name=dw.row.MATCHES_ROLE;a.valid_columns=function(b){if(b[0][d])return{valid:true};return{valid:false,errors:["Invalid comparison"]}};return a};
dw.matches_type=function(d,a){var b=dw.transform();dv.ivar(b,[{name:"lcol",initial:d},{name:"type",initial:a}]);b.test=function(c,e){var f=b._type||c[d].wrangler_type;return!f||!f.parse(c[b._lcol][e])};b.description=function(){return dw.display_name(b._lcol)+" is not a "+a.name};b.valid_columns=function(c){if(c[0][d])return{valid:true};return{valid:false,errors:["Invalid comparison"]}};b.name=dw.row.MATCHES_TYPE;return b};dw.is_missing=function(d){return d===undefined||d===""};
dw.empty=function(){var d=dw.transform();d.test=function(a,b){for(var c,e=0;e<a.cols();++e){c=a[e][b];if(c!=undefined&&(""+c).length)return 0}return 1};d.description=function(a){a=a||{};return a.simple?"empty rows":" row is empty "};d.valid_columns=function(){return{valid:true}};d.name=dw.row.EMPTY;return d};
dw.set_role=function(d,a){var b=dw.transform(d);b._drop=true;dv.ivara(b,[{name:"roles",initial:a||[]}]);b.transform=function(){};b.description=function(){return["Merge",dw.column_clause(b,b._column)," with glue ",dw.input_clause(b,b._glue)]};b.apply=function(c){c=b.getTable(c);b.columns(c).forEach(function(e,f){e.wrangler_role=b._roles[f]});return{}};b.name=dw.transform.SET_ROLE;return b};
dw.set_type=function(d,a){var b=dw.transform(d);dv.ivara(b,[{name:"types",initial:a||[]}]);b.transform=function(){};b.description=function(){return["Merge",dw.column_clause(b,b._column)," with glue ",dw.input_clause(b,b._glue)]};b.apply=function(c){c=b.getTable(c);b.columns(c).forEach(function(e,f){e.wrangler_type=b._types[f]});return{}};b.name=dw.transform.SET_TYPE;return b};
dw.set_name=function(d,a){var b=dw.transform(d);b._drop=true;dv.ivara(b,[{name:"names",initial:a||[]}]);dv.ivar(b,[{name:"header_row",initial:undefined}]);b.transform=function(){};b.well_defined=function(){return b._names.length||b._header_row!=undefined};b.description=function(){if(b._header_row!=undefined){row=b._header_row;if(typeOf(row)==="number")row=dw.row(dw.rowIndex([b._header_row]));return["Promote row",dw.key_clause(b,[b._header_row],"header_row")," to header"]}else return["Set ",dw.column_clause(b,
b._column,"column",{extra_text:""})," name to ",dw.input_clause(b,"names")]};b.apply=function(c){c=b.getTable(c);var e=b.columns(c);if(b._header_row!=undefined){var f=c.row(b._header_row);c.forEach(function(g,h){h=f[h];if(h==undefined||h.length==0)h="undefined";g.setName(h);b._drop&&g.splice(b._header_row,1)});return{promoteRows:[-1,b._header_row]}}else e.forEach(function(g,h){g.setName(a[h])});return{}};b.name=dw.transform.SET_NAME;return b};
dw.role=function(){var d=dw.transform();d.parse=function(){return true};return d};dw.role.GEO="geo";dw.role.STATE="state";dw.geo=function(){var d=dw.role();d.name=dw.role.GEO;return d};
dw.geo.states=["Alabama","Alaska","American Samoa","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Guam","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Northern Marianas Islands","Ohio","Oklahoma","Oregon","Pennsylvania","Puerto Rico",
"Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Virgin Islands","Washington","West Virginia","Wisconsin","Wyoming"];dw.state=function(){var d=dw.geo();d.parse=function(a){return dw.geo.states.indexOf(a)!=-1};d.name=dw.role.STATE;return d};dw.type=function(){var d=dw.transform();d.missing=function(a){return a===undefined||a===""||a===" "};return d};
dw.number=function(){var d=dw.type();d.parse=function(a){var b=Number(a);if(!(isNaN(b)||!b&&(a+"").indexOf("0")===-1))return b};d.comparison=function(){return dw.merge_sort.numberCompare};d.name=dw.transform.NUMBER;return d};dw.string=function(){var d=dw.type();d.parse=function(a){return a};d.name=dw.transform.STRING;d.comparison=function(){return dw.merge_sort.stringCompare};return d};
dw.date=function(){var d=dw.type();d.parse=function(a){var b=Date.parse(a);if(!isNaN(a))return b};d.comparison=function(){return dw.merge_sort.getDateComparison()};d.name=dw.transform.DATE;return d};dw.integer=function(){var d=dw.type();d.parse=function(a){var b=Number(a);if(!(isNaN(b)||!b&&(a+"").indexOf("0")===-1||parseInt(b)!=b))return b};d.comparison=function(){return dw.merge_sort.numberCompare};d.name=dw.transform.INT;return d};
dw.summary=function(d){var a;if(a=cache.get(undefined,d))return a;a=d.wrangler_type||dw.string();for(var b=[],c=[],e=[],f={},g=0;g<d.table.rows();++g){var h=d[g];if(a.missing(h))c.push(g);else a.parse(h)===undefined?b.push(g):e.push(g);f[h]=1}a={missing:c,bparse:b,brole:[],valid:e,unique:f};cache.set(undefined,d,a);return a};dw.summary.clear_cache=function(){cache.clear()};
dw.summary.cache=function(){var d=[];d.set=function(a,b,c){d[b.name]=c;return d};d.get=function(a,b){return d[b.name]};d.clear=function(){d=[]};return d};var cache=dw.summary.cache();dw.LEFT="left";dw.UP="up";dw.DOWN="down";dw.RIGHT="right";
dw.translate=function(d){var a=dw.transform(d);dv.ivar(a,[{name:"direction",initial:dw.DOWN},{name:"values",initial:1}]);a.description_length=function(){if(a._row)return a._row.description_length();return 0};a.description=function(){return["Translate",dw.column_clause(a,a._column),dw.select_clause(a,{select_options:{up:"up",down:"down"},param:"direction"})]};a.apply=function(b){var c=a.getTable(b);b=a.columns(c);c.rows();a._row||dw.row();var e=[];b.forEach(function(f){var g=f.index();if(a._direction===
dw.DOWN)var h;switch(a._direction){case dw.DOWN:h=f.slice(0);h.unshift(undefined);break;case dw.UP:h=f.slice(1);break}h.name="translate";h.type=f.type;h.wrangler_type=f.wrangler_type;h.wrangler_role=f.wrangler_role;c.addColumn(h.name,h,h.type,h.wrangler_type,h.wrangler_role,{index:g+1});e.push(h)});return{newCols:e}};a.enums=function(){return["direction"]};a.name=dw.transform.TRANSLATE;return a};
dw.split=function(d){var a=dw.textPattern(d);dv.ivar(a,[{name:"quote_character",initial:undefined}]);a._drop=true;a.transform=function(b){if(a._positions&&a._positions.length){if(b[0]===undefined)return[];var c=""+b[0];b=a._positions;var e=b[0],f=b[1]||b[0];b=[];b.push(c.substring(0,e));b.push(c.substring(f));b.stats=[{splits:[{start:e,end:f}]}]}else{if((e=a._quote_character)!=undefined)c=new RegExp(e+"[^"+e+"]*"+e);c=dw.regex.match(b[0],{which:a._which,max_splits:a._max,before:a._before,after:a._after,
on:a._on,ignore_between:c||a._ignore_between});b=[];b.stats=[];for(e=0;e<c.length;++e)e%2==0?b.push(c[e].value):b.stats.push({splits:[{start:c[e].start,end:c[e].end}]})}return b};a.description=function(){var b=["Split",dw.column_clause(a,a._column,"column",{editor_class:"none"})];if(Number(a._max)===0)b=b.concat(dw.select_clause(a,{select_options:{"0":"repeatedly","1":"once"},param:"max"}));regex=a.match_description();b=b.concat(regex);if(a._result===dw.ROW){b=b.concat(" into ");b=b.concat(dw.select_clause(a,
{select_options:{row:"rows"},param:"result"}))}return b};a.name=dw.transform.SPLIT;return a};
dw.textPattern=function(d){var a=dw.map(d);dv.ivar(a,[{name:"on",initial:undefined},{name:"before",initial:undefined},{name:"after",initial:undefined},{name:"ignore_between",initial:undefined},{name:"which",initial:1},{name:"max",initial:1}]);dv.ivara(a,[{name:"positions",initial:undefined}]);a.well_defined=function(){return(a._positions&&!a._on&&!a._before&&!a._after||!a._positions&&(a._on||a._before||a._after))&&!a._row};a.description_length=function(){if(a._positions)return 0;return dw.regex.description_length(a._on)+
dw.regex.description_length(a._before)+dw.regex.description_length(a._after)};a.check_validity=function(b){b=a.valid_columns(b);return b.valid?a.well_defined()?{valid:true}:{valid:false,errors:["Must define split criteria"]}:b};a.match_description=function(b){b=b||{};var c=[];if(a._positions)return["between positions",dw.column_clause(a,a._positions,b)];if(a._on&&a._on.toString()!="/.*/")c=c.concat(["on",dw.regex_clause(a,"on",b)]);if(a._before&&!a._after)c=c.concat(["before",dw.regex_clause(a,"before",
b)]);if(a._after&&!a._before)c=c.concat(["after",dw.regex_clause(a,"after",b)]);if(a._after&&a._before)c=c.concat(["between",dw.regex_clause(a,"after",b),"and",dw.regex_clause(a,"before",b)]);return c};return a};
dw.edit=function(d){var a=dw.textPattern(d);a._update=true;dv.ivar(a,[{name:"to",initial:undefined},{name:"update_method",initial:undefined}]);a.transform=function(b){var c;if(a._to!=undefined)c=function(){return a._to};else if(a._update_method)switch(a._update_method){case dw.edit.upper:c=function(e){return e.toUpperCase()};break;case dw.edit.lower:c=function(e){if(e!=undefined)return e.toLowerCase()};break;case dw.edit.capitalize:c=function(e){if(e!=undefined)if(e.length>=1)return e[0].toUpperCase()+
e.substr(1)};break;case dw.edit.uncapitalize:c=function(e){if(e!=undefined)if(e.length>=1)return e[0].toLowerCase()+e.substr(1)};break;default:throw"Illegal update update_method";}return b.map(function(e){return e!=undefined?""+e:undefined}).map(c)};a.description=function(){var b=["Edit",dw.column_clause(a,a._column,"column",{editor_class:"none"})];regex=a.match_description();b=b.concat(regex);a._row&&b.push(dw.row_clause(a,a._row,"row"));if(a._to!=undefined){b.push(" to '");b.push(dw.input_clause(a,
"to"));b.push("'")}else a._update_method&&b.push(dw.select_clause(a,{select_options:{LOWER:" to lowercase",CAPITALIZE:" capitalize",UNCAPITALIZE:" uncapitalize",UPPER:"to uppercase"},param:"update_method"}));return b};a.well_defined=function(){return a._column.length===1&&(a._to!=undefined||a._update_method!=undefined)};a.name=dw.transform.EDIT;return a};dw.edit.upper="UPPER";dw.edit.lower="LOWER";dw.edit.capitalize="CAPITALIZE";dw.edit.uncapitalize="UNCAPITALIZE";dw.INSERT_RIGHT="right";
dw.INSERT_END="end";dw.ROW="row";dw.COLUMN="column";dw.clause={column:"column",regex:"regex",input:"input",array:"array",select:"select"};dw.status={active:"active",inactive:"inactive",deleted:"deleted",invalid:"invalid"};
dw.transform=function(d){var a={};a.is_transform=true;dv.ivara(a,{name:"column",initial:d!=undefined?d:[]});dv.ivar(a,[{name:"table",initial:0},{name:"status",initial:dw.status.active},{name:"drop",initial:false}]);a.getTable=function(b){return b[a.table()]};a.show_details=false;a.active=function(){return a._status===dw.status.active};a.inactive=function(){return a._status===dw.status.inactive};a.deleted=function(){return a._status===dw.status.deleted};a.invalid=function(){return a._status===dw.status.invalid};
a.toggle=function(){a.active()?a.status(dw.status.inactive):a.status(dw.status.active)};a.delete_transform=function(){a._status=dw.status.deleted};a.errors=[];a.invalidate=function(b){a._status=dw.status.invalid;a.errors=b};a.validate=function(){a._status=dw.status.active;a.errors=[]};a.errorMessage=function(){return a.errors.join("\n")};a.columns=function(b){if(a._column&&a._column.length)return a._column.map(function(c){return b[c]});return b.map(function(c){return c})};a.has_parameter=function(b){return a[b]!=
undefined};a.well_defined=function(){return true};a.params=function(){return dv.keys(a).filter(function(b){return b[0]==="_"})};a.enums=function(){return[]};a.param_equals=function(b,c){if(b===undefined||c===undefined)return b===c;ktype=typeOf(b);switch(ktype){case "function":return b.toString()===c.toString();case "array":if(b.length!=c.length)return false;for(var e=0;e<b.length;++e)if(!a.param_equals(b[e],c[e]))return false;return true;case "object":if(b.equals)return b.equals(c);return b.toString()===
c.toString();case "number":case "string":case "boolean":return b===c;default:return b===c}};a.similarity=function(b){for(var c=a.name!=b.name?-1:0,e=a.params(),f=b.params(),g,h,j=0,i=0;i<e.length;++i){g=a[e[i]];h=b[f[i]];a.param_equals(g,h)&&j++}return c+j/e.length};a.equals=function(b){if(a.name!=b.name)return false;for(var c=a.params(),e=b.params(),f,g,h=0;h<c.length;++h){f=a[c[h]];g=b[e[h]];if(!a.param_equals(f,g))return false}return true};a.check_validity=function(b){return a.valid_columns(b)};
a.valid_columns=function(b){b=a.getTable(b);if(a.columns(b).filter(function(c){return c===undefined}).length)return{valid:false,errors:["Invalid columns"]};return{valid:true}};a.clone_param=function(b){switch(typeOf(b)){case "function":return b;case "array":return b.map(function(c){return a.clone_param(c)});case "object":if(b.clone)return b.clone();return b;case "number":case "string":case "boolean":return b;default:return b}};a.default_transform=function(){return dw.transform.create(a.name)};a.clone=
function(){for(var b=a.default_transform(),c=a.params(),e,f=0;f<c.length;++f){e=a[c[f]];b[c[f]]=a.clone_param(e)}return b};a.description_length=function(){return 0};a.comment=function(){return a.description().map(function(b){if(typeOf(b)==="string")return b;return b.description()}).join(" ")};a.sample_apply=function(b){return a.apply(b,{max_rows:1E3,warn:true})};return a};dw.transform.create=function(d){return dw[d]()};
dw.transform.tableUpdate=function(d,a,b){var c={},e=d.result();if(e===dw.COLUMN){c.finish=function(){d._drop&&d.columns(a).forEach(function(k){a.removeColumn(k.name)})};if(d.update()){c.update=function(k,m){for(var n=0;n<m.length;++n)b[n][k]=m[n]};c.stats=function(){return{updatedCols:b}}}else{var f=[],g;switch(d.insert_position()){case dw.INSERT_RIGHT:g=b[b.length-1].index();break;case dw.INSERT_END:g=a.length;break}c.update=function(k,m){for(var n=0;n<m.length;++n){if(n===f.length){var u=[];f.push(u);
a.addColumn(d.name,u,dv.type.nominal,dw.string(),dw.role(),{index:g+f.length})}f[n][k]=m[n]}};c.stats=function(){return{newCols:f}}}}else if(e===dw.ROW){var h=0,j=a.map(function(k){var m=[];m.name=k.name;m.type=k.type;return m}),i=b[0].index();c.update=function(k,m){for(var n=0;n<m.length;++n){for(var u=0;u<i;++u)j[u][h]=a[u][k];for(u=i+1;u<j.length;++u)j[u][h]=a[u][k];j[i][h]=m[n];++h}return j[0].length};c.finish=function(){for(;a.cols();)a.removeColumn(0);j.forEach(function(k){a.addColumn(k.name,
k,k.type)})};c.stats=function(){return{}}}return c};dw.transform.SPLIT="split";dw.transform.EXTRACT="extract";dw.transform.CUT="cut";dw.transform.MERGE="merge";dw.transform.FOLD="fold";dw.transform.UNFOLD="unfold";dw.transform.FILL="fill";dw.transform.FILTER="filter";dw.transform.DROP="drop";dw.transform.ROW="row";dw.transform.COPY="copy";dw.transform.LOOKUP="lookup";dw.transform.TRANSLATE="translate";dw.transform.EDIT="edit";dw.transform.SORT="sort";dw.transform.TRANSPOSE="transpose";
dw.transform.STRING="string";dw.transform.INT="int";dw.transform.NUMBER="number";dw.transform.DATE="date";dw.transform.SET_TYPE="set_type";dw.transform.SET_ROLE="set_role";dw.transform.SET_NAME="set_name";
dw.unfold=function(d){var a=dw.transform(d);dv.ivar(a,[{name:"measure",initial:undefined}]);a.description=function(){return["Unfold",dw.column_clause(a,a._column,"column",{editor_class:"unfold",single:true})," on ",dw.column_clause(a,[a._measure],"measure",{single:true})]};a.apply=function(b,c){c=c||{};var e=a.getTable(b);b=a.columns(e);var f=b.map(function(E){return E.name}),g=e.map(function(E){return E.name}).filter(function(E){return f.indexOf(E)===-1&&a._measure!=E}),h=e.rows(),j,i=[e[a._measure]],
k=c.max_rows||1E3,m=c.start_row||0,n=c.end_row||h;n=Math.min(h,n);c=e.slice(m,n,{compress:true,compressAll:true}).query({dims:f.concat(g),vals:[dv.first(a._measure)],warn:c.warn});h=c[0].unique;var u=f.length,x=c.length-1,y=g.length,B=[];dv.range(0,h+g.length).forEach(function(){B.push([])});j=c[0].length;if(k&&k<j)j=k;for(m=m;m<n;++m){k=Math.floor(m/h);for(j=0;j<g.length;++j)B[j][k]=c[u+j][m];j=B[y+m%h];j.name=c[0][m];j[k]=c[x][m]}n=e.cols();for(c=0;c<n;++c)e.removeColumn(0);var F,v=[];B.forEach(function(E,
s){F=s<y?g[s]:E.name;e.addColumn(F,E,dv.type.nominal);s>=y&&v.push(E.name)});return{toKeyRows:[-1],toHeaderCols:b,toValueCols:i,valueCols:v.map(function(E){return e[E]}).filter(function(E){return E!=undefined})}};a.description_length=function(){if(a._measure==="State")return 1;return 0};a.well_defined=function(b){if(a._column&&a._column.length===1&&a._measure&&a._measure!=a._column[0]&&(!b||b.length>=3))return true;return false};a.check_validity=function(b){var c=a.valid_columns(b);return c.valid?
a.getTable(b)[a._measure]?{valid:true}:{valid:false,errors:["Invalid Measure"]}:c};a.name=dw.transform.UNFOLD;return a};
dw.transpose=function(d){var a=dw.transform(d);dv.ivara(a,[]);a.description_length=function(){return 0};a.description=function(){return["Transpose table"]};a.apply=function(b,c){c=c||{};var e=a.getTable(b);a.columns(e);e.rows();a._row||dw.row();b=dv.range(0,e.rows()).map(function(){var h=[];h.name="transpose";h.type=dv.type.nominal;return h});for(c=0;c<e.cols();++c)for(var f=e[c],g=0;g<e.rows();++g)b[g][c]=f[g];for(;e.cols();)e.removeColumn(0);b.forEach(function(h){e.addColumn(h.name,h,h.type,dw.string(),
undefined,{})});return{}};a.name=dw.transform.TRANSPOSE;return a};
dw.sort=function(d){var a=dw.transform(d);dv.ivara(a,[{name:"direction",initial:[]},{name:"as_type",initial:[]}]);a.description_length=function(){return 0};a.description=function(){var b=["Sort by ",dw.column_clause(a,a._column,"column")];a._direction&&a._direction.length&&a._direction[0]==="desc"&&b.push(a._direction[0]);return b};a.apply=function(b,c){c=c||{};b=a.getTable(b);var e=a.columns(b);b.rows();c=a._row||dw.row();var f=e.map(function(n){n=a._as_type[0]||n.wrangler_type;if(!n)return dw.stringCompare;
return n.comparison()}),g=[];for(c=0;c<e.length;++c)a._direction[c]==="desc"?g.push(-1):g.push(1);for(var h=dw.merge_sort(dv.range(0,b.rows()),function(n,u){for(var x=0;x<f.length;++x){var y=e[x];y=f[x](y[n],y[u]);if(y!=0)return g[x]*y}if(n<u)return-1;if(n==u)return 0;return 1}),j=b.slice(),i=0;i<b.length;++i){var k=b[i],m=j[i];for(c=0;c<b.rows();++c)k[c]=m[h[c]]}return{updatedCols:e}};a.name=dw.transform.SORT;return a};
dw.preview=function(d,a,b,c,e){var f=d.visible_rows(),g=Math.max(0,f[0]),h=Math.max(0,f[1]),j=a.slice();dw.wrangle();a.names();var i,k,m;d.container().removeClass("previewBeforeTable").removeClass("updatedTable");c.container().removeClass("previewAfterTable").addClass("hidden").hide();if(b){f=b.drop();b.drop(false);b.name===dw.transform.CUT&&b.update(false);h=b.apply([j],{max_rows:1E3,start_row:g,end_row:h});var n=h.newCols||[],u=h.updatedCols||[],x=h.droppedCols||[],y=h.toValueCols||[],B=h.toHeaderCols||
[],F=h.toKeyRows||[],v=h.keyRows||[],E=h.valueCols||[],s=h.keyCols||[],z=h.promoteRows||[],C=(h.valueStats||[]).map(function(q){if(q)return q[0]&&q[0].splits});effectedRows=h.effectedRows||[];columnTable=j;b.name===dw.transform.CUT&&b.update(true);switch(b.name){case dw.transform.FOLD:case dw.transform.UNFOLD:case dw.transform.TRANSPOSE:d.container().addClass("previewBeforeTable");d.schema_table(a).table(a).draw();c.table(j).draw();c.container().addClass("previewAfterTable").show();columnTable=a;
break;case dw.transform.FILTER:d.container().addClass("updatedTable");d.schema_table(a).table(a).draw();break;case dw.transform.SPLIT:case dw.transform.CUT:case dw.transform.EXTRACT:highlightClass=b.name+"Highlight";default:d.container().addClass("updatedTable");d.schema_table(a).table(j).draw()}var l,p,r,o;b.column().forEach(function(q){i=columnTable[q];m=i.index();l=jQuery(".updatedTable td:nth-child("+(m+2)+")");for(q=0;q<C.length;++q)if(o=C[q]){if(p=l[q])p=p.firstChild;else break;r=i[q+g];p&&
r!=undefined&&o[0]&&r.length>=o[0].end&&Highlight.highlight(p,o[0].start,o[0].end,{highlightClass:highlightClass})}});n.forEach(function(q){jQuery(".updatedTable td:nth-child("+(q.index()+2)+")").addClass("previewNew").addClass("unclickable")});x.forEach(function(q){jQuery(".updatedTable td:nth-child("+(q.index()+2)+")").addClass("previewDeleted")});B.forEach(function(q){m=a[q.name].index();jQuery(".previewBeforeTable td:nth-child("+(m+2)+")").addClass("previewSchema")});u.forEach(function(q){i=a[q.name];
k=j[q.name];m=i.index();q=dv.range(0,a.rows());d.rows(function(w,t){k[t]!=undefined&&i[t]!==k[t]&&w.find("td:nth-child("+(m+2)+")").addClass("previewNew")},q)});d.rows(function(q){q.addClass("previewDeleted")},effectedRows);d.rows(function(q){q.addClass("previewKey")},z);y.forEach(function(q){m=a[q.name].index();jQuery(".previewBeforeTable td:nth-child("+(m+2)+")").addClass("previewNew");d.rows(function(w,t){t===-1?jQuery(".previewBeforeTable tr:nth-child(2) th:nth-child("+(m+2)+")").addClass("previewKey"):
w.find("td:nth-child("+(m+2)+")").addClass("previewKey")},v)});E.forEach(function(q){m=j[q.name].index();jQuery(".previewAfterTable td:nth-child("+(m+2)+")").addClass("previewNew");c.rows(function(w,t){t===-1?jQuery(".previewAfterTable tr:nth-child(2) th:nth-child("+(m+2)+")").addClass("previewKey"):w.find("td:nth-child("+(m+2)+")").addClass("previewKey")},F)});s.forEach(function(q){m=j[q.name].index();jQuery(".previewAfterTable td:nth-child("+(m+2)+")").addClass("previewKey")});b.drop(f)}else d.schema_table(a).table(a).draw();
e.draw();jQuery(".unclickable").unbind("mouseup").unbind("mousedown")};
dw.table_selection=function(d){var a={},b=dw.selection(),c=dw.selection();a.add=function(e){var f;if(e.shift)f=dw.selection.shift;else if(e.ctrl)f=dw.selection.ctrl;switch(e.type){case dw.engine.row:b.add({type:f,selection:e.position.row});c.clear();break;case dw.engine.col:c.add({type:f,selection:e.table[e.position.col].index()});b.clear();break;default:}return a};a.clear=function(){b.clear();c.clear()};a.draw=function(){d.rows(function(e){e.addClass("selected")},b);d.cols(function(e){e.addClass("selected")},
c);return a};a.selection=function(){return{rows:b,cols:c}};a.rows=function(){return b.slice(0)};a.cols=function(){return c.slice(0)};return a};dw.table_selection.row="row";dw.table_selection.col="col";
dw.selection=function(){var d=[],a=[];d.add=function(b){var c=b.selection,e;switch(b.type){case dw.selection.ctrl:e=d.indexOf(c);e===-1?d.push(c):d.splice(e,1);break;case dw.selection.shift:if(d.length){e=a[a.length-1];if(e.type!=dw.selection.clear){c=e.selection<c?dv.range(e.selection,c+1):dv.range(c,e.selection+1);c.forEach(function(f){d.indexOf(f)===-1&&d.push(f)})}}else d.push(c);break;case dw.selection.clear:d.length=0;break;default:d.length=0;d.push(c)}a.push(b);return d};d.clear=function(){d.add({type:dw.selection.clear})};
return d};dw.selection.ctrl="ctrl";dw.selection.shift="shift";dw.selection.clear="clear";
dw.vtable=function(d,a){d=jQuery(d);a=a||{};var b={},c,e,f,g,h={},j=a.interaction,i=a.ontablechange,k=a.onexecute,m=a.onconfirm,n;b.schema_table=function(s){if(arguments.length){n=s;return b}else{if(n)return n;return e}};var u=0;b.row_offset=function(s){if(arguments.length){u=s;return b}return u||0};dv.ivar(b,[{name:"page",initial:0},{name:"page_length",initial:25}]);b.table=function(s){var z,C,l,p;e=s.slice_cols(0,40);f=[];for(l=0;l<s.rows();++l)f.push([l+1]);for(C=0;C<e.cols();++C){z=s[C];for(l=
0;l<s.rows();++l){p=z[l];f[l][C+1]=p===undefined?"":p}}var r;g=[{sTitle:""}].concat(e.map(function(o){r=o.name;return{sTitle:r,sWidth:"30px"}}));return b};b.draw=function(){g.length>39&&m&&m({message:"You are creating a lot of columns."});var s=d.attr("id")+"_table";c&&c.fnDestroy();d.html('<table cellpadding="0" cellspacing="0" border="0" class="display" id="'+s+'"></table>');c=$("#"+s).dataTable({aaData:f,aoColumns:g,aaSorting:[],iDisplayStart:b.page()*b.page_length(),iDisplayLength:b.page_length(),
aoColumnDefs:[{bSortable:false,aTargets:["_all"]}],sDom:'rt<"clear">',sScrollY:"85%"});var z,C=false;d.find("td").mouseup(function(w){if(jQuery(this).index()){if(this===z){var t=E();jQuery(this).parent();var D=v(this);w=e[D.col][D.row];if(t&&w&&w.length>t.startCursor)if(t){D=v(this);D.col=e[D.col].name;setTimeout(function(){if(!C){b.save_settings();j({type:dw.engine.highlight,position:D,selection:t})}},t.startCursor===t.endCursor?200:0)}}}else{b.save_settings();j({type:dw.engine.row,position:v(this),
shift:w.shiftKey,ctrl:w.metaKey})}}).mousedown(function(w){Highlight.removeHighlight(w.currentTarget);z=this}).dblclick(function(w){C=true;var t=dw.jq("input"),D=this;jQuery(w.currentTarget).empty().append(t);var G=v(D);t.css("width","100%").css("height","16px").focus().val(e[G.col][G.row]);t.blur(function(){b.save_settings();j({type:dw.engine.edit,position:G,val:t.val(),table:e})}).keydown(function(H){H.stopImmediatePropagation();t.unbind("blur");switch(H.which){case 13:b.save_settings();j({type:dw.engine.edit,
position:G,val:t.val(),table:e});break}})});var l=false;d.find(".dataTables_scrollHead th").click(function(w){var t=this;setTimeout(function(){if(!l){b.save_settings();j({type:dw.engine.col,position:{row:-1,col:e[jQuery(t).index()-1].name},table:e,shift:w.shiftKey,ctrl:w.metaKey})}},200)}).dblclick(function(w){var t=dw.jq("input"),D=this;jQuery(w.currentTarget).empty().append(t);t.css("width","100%").css("height","16px").focus().val(dw.display_name(e[jQuery(D).index()-1].name));t.blur(function(){b.save_settings();
k(dw.set_name(e[jQuery(D).index()-1].name,[t.val()]))}).keydown(function(G){if(G.which===13){t.unbind("blur");b.save_settings();k(dw.set_name(e[jQuery(D).index()-1].name,[t.val()]))}});l=true}).slice(1).append(dw.jq("span").addClass("column_sort_status"));b.add_sort_status();var p=dw.jq("tr").append(dw.jq("th")),r;d.find(".dataTables_scrollHead thead").prepend(p);var o=[];e.forEach(function(){r=dw.jq("th");p.append(r);o.push(r)});s=b.width();d.find("table").width(s).css("overflow-x","hidden");d.width(s+
30).css("max-width",s+30).css("margin","0px");d.find("table").parent().width(s+30).css("max-width",s+30).css("margin","0px");d.find(".dataTables_scrollHead").width(s+30).css("max-width",s+30).css("margin","0px");s=b.column_width();d.find("th,td").css("width",s).css("max-width",s).css("min-width",s).css("padding","0px");d.find("th:nth-child(1),td:nth-child(1)").css("width","30px").css("max-width","30px").css("min-width","30px").css("padding","0px").addClass("rowHeader");d.find(".dataTables_scrollBody").css("overflow-x",
"hidden");e.forEach(function(w,t){B(o[t],w)});y();x();s=jQuery(".ui-layout-center");var q=h.scrollLeft;q!=undefined&&s.scrollLeft(q);jQuery(".ui-layout-center").scroll(function(){b.save_settings()});return b};b.save_settings=function(){var s=jQuery(".ui-layout-center");h.scrollLeft=jQuery(s).scrollLeft()};b.column_width=function(){return e.length===1?800:e.length===2?400:e.length===3?266:200};b.width=function(){return e.length*b.column_width()+30};b.visible_rows=function(){var s=b.page()*b.page_length(),
z=s+b.page_length();return[s,z]};b.add_sort_status=function(){d.find(".column_sort_status").addClass("column_sort_unsorted");if(a.wrangler){var s,z=a.wrangler.filter(function(C){return C.active()&&C.name===dw.transform.SORT});if(z=z[z.length-1]){s=z.column();d.find(".column_sort_status").each(function(){if(e[jQuery(this).parent().index()-1]===e[s])z.direction()[0]==="desc"?jQuery(this).removeClass("column_sort_unsorted").addClass("column_sort_desc").click(function(C){C.stopPropagation();C.stopImmediatePropagation();
k(dw.sort(e[jQuery(this).parent().index()-1].name).direction("asc").as_type([e[jQuery(this).parent().index()-1].wrangler_type]))}):jQuery(this).removeClass("column_sort_unsorted").addClass("column_sort_asc").click(function(C){C.stopPropagation();C.stopImmediatePropagation();k(dw.sort(e[jQuery(this).parent().index()-1].name).direction("desc").as_type([e[jQuery(this).parent().index()-1].wrangler_type]))})})}d.find(".column_sort_unsorted").click(function(C){C.stopPropagation();C.stopImmediatePropagation();
k(dw.sort(e[jQuery(this).parent().index()-1].name).as_type([e[jQuery(this).parent().index()-1].wrangler_type]))})}};var x=function(){if(b.page_length()<b.schema_table().rows())var s=dw.jq("span").addClass("next").addClass("paginate_button").append("Next").click(function(){b.page(b.page()+1);b.save_settings();i()}),z=dw.jq("span").addClass("next").addClass("paginate_button").append("Prev").click(function(){if(b.page()){b.page(b.page()-1);b.save_settings();i()}});var C=dw.jq("span").addClass("table_size_indicator").append("Total rows: "+
e.rows());d.append(C).append(z).append(s)},y=function(){var s,z,C;b.header_row().slice(1).each(function(l,p){z=e[l].wrangler_role;s=e[l].wrangler_type||dw.string();C=z&&z.name?z.name:s.name;jQuery(p).addClass(C).addClass("icon")})};b.header_row=function(){return d.find(".dataTables_scrollHead tr:nth-child(2) th")};var B=function(s,z){var C=s.width(),l=dw.summary(z);C=b.column_width();var p=normalized_summary=F(z,l,5,C);d3.scale.linear().domain([0,1]).range([0,C]);d3.scale.ordinal().domain(d3.range(p.length)).rangeBands([0,
15],0.2);var r=function(o,q){o=o[q.type].length;switch(q.type){case "missing":case "valid":return o+" "+q.type+" "+(o===1?"value":"values");case "bparse":return o+" "+(o===1?"value":"values")+" don't parse";case "brole":return o+" "+(o===1?"value":"values")+" don't match role"}};d3.select(s[0]).append("svg:svg").attr("width",C).attr("height",15).selectAll("g.bar").data(p).enter("svg:g").attr("class","bar").attr("transform",function(o,q){return"translate("+normalized_summary.slice(0,q).reduce(function(w,
t){return w+t.val},0)+",0)"}).append("svg:rect").attr("class",function(o){return o.type}).attr("width",function(o){return o.val}).attr("height",15).on("mouseup",function(o){j({type:o.type,col:e[z.index()].name})}).append("svg:title").text(function(o){return r(l,o)})},F=function(s,z,C,l){var p=[],r=s.table.rows(),o,q,w=0,t;o=dv.keys(z).filter(function(D){return D!="unique"}).filter(function(D){return z[D].length!=0}).length;q=l-o*C;["valid","brole","bparse","missing"].forEach(function(D){t=Math.round(z[D].length===
0?0:C+q*(z[D].length-1)/(r-o));p.push({type:D,val:t});w+=t});return p},v=function(s){s=c.fnGetPosition(s);if(typeOf(s==="array"))return{row:s[0],col:s[1]-1};return{row:s}},E=function(){var s=window.getSelection();if(s)try{var z=s.getRangeAt(0);return{startCursor:z.startOffset,endCursor:z.endOffset}}catch(C){}};b.id=function(){return d.attr("id")+"_table"};b.rows=function(s,z){var C=b.id(),l=b.page()*b.page_length(),p=l+b.page_length(),r;z.filter(function(o){return o>=l&&o<p||o===-1}).forEach(function(o){if(o===
-1)return s(jQuery("#"+C+" thead tr:nth-child(2)"),o);r=(o+1)%b.page_length();if(r===0)r=b.page_length();return s(jQuery("#"+C+" tr:nth-child("+r+")"),o)})};b.cols=function(s,z){var C=b.id();z.forEach(function(l){s(jQuery("#"+C+" td:nth-child("+(l+2)+")"),l)})};b.container=function(){return d};return b};
dw.wrangler_export=function(d,a){a=a||{};switch(a.format||"csv"){case "csv":return dw.wrangler_export.csv(d);case "tsv":return dw.wrangler_export.tsv(d);case "rowjson":return dw.wrangler_export.rowjson(d);case "columnjson":return dw.wrangler_export.coljson(d);case "python":return dw.wrangler_export.python(a.wrangler);case "javascript":return dw.wrangler_export.javascript(a.wrangler)}};
dw.wrangler_export.csv=function(d){var a="";a+=d.names().map(dw.display_name).join(",")+"\n";for(var b=0;b<d.rows();++b)a+=d.row(b).join(",")+"\n";return a};dw.wrangler_export.tsv=function(d){var a="";a+=d.names().map(dw.display_name).join("\t")+"\n";for(var b=0;b<d.rows();++b)a+=d.row(b).join("\t")+"\n";return a};
dw.wrangler_export.coljson=function(d){var a="[";a+=d.map(function(b){return'{name: "'+dw.display_name(b.name)+'", values: ['+b.map(function(c){if(Number(c)!=c)c="'"+c+"'";return c}).join(",")+"]}\n"}).join(",");a+="]";return a};dw.wrangler_export.rowjson=function(d){for(var a="[",b,c=0;c<d.rows();++c){if(c)a+=",\n";a+="{"+d.map(function(e){b=e[c];if(b===undefined)b="";if(Number(b)!=b)b="'"+b+"'";return dw.display_name(e.name)+": "+b}).join(",")+"}"}a+="]";return a};
dw.wrangler_export.javascript=function(d){var a=function(c){if(c===true)return"true";if(c===false)return"false";if(c===undefined)return"undefined";if(typeOf(c)==="object"||typeOf(c)==="function"){if(c.is_transform)return b(c);return JSON.stringify(c.toString().replace(/^\/|\/$/g,""))}if(typeOf(c)==="array")return"["+c.map(a)+"]";return JSON.stringify(c)},b=function(c){var e="dw."+c.name+"()",f=c.params().map(function(g){return"."+g.substr(1)+"("+a(c[g])+")\n"}).join("\t");return e+f};return"w = dw.wrangle()\n"+
d.filter(function(c){return c.active()}).map(function(c){return"w.add("+b(c)+")"}).join("\n")+"\n\nw.apply([t])\n\n\n"};
dw.wrangler_export.python=function(d){var a=function(c){if(c===true)return"True";if(c===false)return"False";if(c===undefined)return"None";if(typeOf(c)==="object"||typeOf(c)==="function"){if(c.is_transform)return b(c);return dw.JSON.stringify(c.toString().replace(/^\/|\/$/g,""))}if(typeOf(c)==="array")return"["+c.map(a)+"]";return dw.JSON.stringify(c)},b=function(c){var e=c.name.split("_").map(function(g){return g.charAt(0).toUpperCase()+g.slice(1)}).join(""),f="dw."+e+"(";e=c.params().map(function(g){return g.substr(1)+
"="+a(c[g])}).join(",\n"+dv.range(0,10+e.length).map(function(){return" "}).join(""));return f+e+")"};return"from wrangler import dw\nimport sys\n\nif(len(sys.argv) < 3):\n\tsys.exit('Error: Please include an input and output file.  Example python script.py input.csv output.csv')\n\nw = dw.DataWrangler()\n"+d.filter(function(c){return c.active()}).map(function(c){return"\n# "+c.comment()+"\nw.add("+b(c)+")"}).join("\n")+"\n\nw.apply_to_file(sys.argv[1]).print_csv(sys.argv[2])\n\n"};
dw.corpus=function(){var d={};d.frequency=function(a,b){b=b||{};b=b.inputs||[];if(b=b[b.length-1])switch(b.type){case dw.engine.highlight:if(b&&b.params.start!=undefined)if(b.params.end-b.params.start>1)switch(a.name){case dw.transform.SPLIT:return 9;case dw.transform.EXTRACT:return 24;case dw.transform.CUT:return 10;case dw.transform.FILTER:return 8}break;case dw.engine.row:for(var c=dw.row(dw.empty()),e=0;e<b.params.rows.length;++e)if(c.test(b.params.table,b.params.rows[e]))if(a.name===dw.transform.FILL)return 0}switch(a.name){case dw.transform.SPLIT:return 35;
case dw.transform.EXTRACT:return 32;case dw.transform.CUT:return 28;case dw.transform.DROP:return 13;case dw.transform.FOLD:return 12;case dw.transform.UNFOLD:if(b&&b.params.table.length>3)return 0;return 8;case dw.transform.SET_NAME:return 4;case dw.transform.SHIFT:return 5;case dw.transform.FILL:return 21;case dw.transform.MERGE:return 3;case dw.transform.COPY:return 6;case dw.transform.FILTER:return 25}};d.top_transforms=function(a){a=a||{};var b=a.transform,c=a.given_params,e=a.needed_params;
a=a.table;switch(b.name){case dw.transform.FILL:if(c.indexOf("column")===-1&&e.indexOf("direction")!=-1){c=b.column();e=b.row();return c&&c.length!=1&&e?[b.clone().direction(dw.RIGHT),b.clone().direction(dw.LEFT),b.clone().direction(dw.DOWN),b.clone().direction(dw.UP)]:[b.clone().direction(dw.DOWN),b.clone().direction(dw.UP),b.clone().direction(dw.LEFT),b.clone().direction(dw.RIGHT)]}else return[b.clone().direction(dw.DOWN),b.clone().direction(dw.UP),b.clone().direction(dw.LEFT),b.clone().direction(dw.RIGHT)];
case dw.transform.FOLD:if(c.indexOf("keys")===-1)return[b.clone().keys([-1]),b.clone().keys([0]),b.clone().keys([0,1]),b.clone().keys([0,1,2])];if(c.indexOf("column")===-1)return[b.clone()].concat(get_columns(a,[dw.integer,dw.string]).map(function(f){return b.clone().column(f)}));return[b.clone()];case dw.transform.UNFOLD:if(c.indexOf("measure")===-1)return get_columns(a,[dw.integer,dw.number,dw.string]).map(function(f){return b.clone().measure(f)});return[b.clone()];default:return[b.clone()]}};get_columns=
function(a,b,c){a=a.slice(0);a.map(function(){});a.sort(function(e,f){e=b.indexOf(e.wrangler_type.name);f=b.indexOf(f.wrangler_type.name);if(e===-1)e=1E6;if(f===-1)f=1E6;if(e<f)return-1;if(f<e)return-1;return 0});return a.slice(0,c).map(function(e){return e.name})};return d};
dw.engine=function(d){var a={};d=d||{};var b=d.transform_set||dw.engine.transform_set,c=d.corpus||dw.corpus(),e;dv.ivar(a,[{name:"table",initial:undefined}]);dv.ivara(a,[{name:"inputs",initial:[]}]);a.run=function(l){var p=s().concat(B()).concat(v()).concat(F());return f(p).slice(0,l)};a.input=function(l){a._inputs.push(l);return a};a.restart=function(){};var f=function(l){var p=C([dw.engine.promote,dw.engine.param]);p=p[p.length-1];var r=[],o=b.slice(0);if(e=p&&p.transform){o=o.filter(function(q){return q.name!=
e.name});o.unshift(e)}r=r.concat(o.reduce(function(q,w){return q.concat(l.filter(function(t){return!t.is_transform}).reduce(function(t,D){return t.concat(m(w,D))},[]))},[]));r=l.filter(function(q){return q.is_transform}).concat(r);r=r.concat(n()).concat(y()).concat(x()).concat(u());r=j(r);r.unshift(e);r=g(r);r=r.slice(0,10).filter(function(q,w){if(w===0||q===undefined)return true;if(r[0]&&q.equals(r[0]))return false;return true});if(r.length===1&&r[0]===undefined)if(p=h())r=[dw[p]()];return r},g=
function(l){for(var p={},r={},o,q,w=[],t=h()||e&&e.name,D=Math.max(Math.ceil(Math.min(6,l.length)*0.33),6),G=0,H=0;H<l.length;++H){o=l[H];if(o!==undefined){q=r[o.name]||0;if(o.name===t)G++;else{r[o.name]=++q;q<=D&&G++}}}r=6-G;for(H=0;H<l.length;++H){o=l[H];if(o===undefined)w.push(o);else{q=p[o.name]||0;if(o.name===t)w.push(o);else{p[o.name]=++q;if(q<=D)w.push(o);else if(r>0){r--;w.push(o)}}}}return w},h=function(){var l=z(dw.engine.filter);return(l=l[l.length-1])?l.transform:undefined},j=function(l){var p=
E();l.forEach(function(w){w.weights={};w.weights.tf=c.frequency(w,{inputs:p});w.weights.td=k(w);w.weights.tdl=i(w);if(e)w.weights.wts=e.similarity(w)});var r,o,q=h();l.sort(function(w,t){r=w.weights;o=t.weights;if(e){if(w.name===e.name&&t.name!=e.name)return-1;if(t.name===e.name&&w.name!=e.name)return 1;if(w.name===e.name&&t.name===e.name){var D=r.wts,G=o.wts;if(D>G)return-1;if(G>D)return 1}}if(q)if(w.name===q&&t.name!=q)return-1;else if(t.name===q&&w.name!=q)return 1;if(r.td>o.td)return-1;if(o.td>
r.td)return 1;if(r.tf>o.tf)return-1;if(o.tf>r.tf)return 1;if(r.tdl<o.tdl)return-1;if(o.tdl<r.tdl)return 1;return 0});return l},i=function(l){return l.description_length()},k=function(l){switch(l.name){case dw.transform.SPLIT:case dw.transform.CUT:case dw.transform.EXTRACT:case dw.transform.FILTER:return 1;default:return 0}},m=function(l,p){if(p.is_transform)return[p];l=l.clone();for(var r=dv.keys(p),o,q=0;q<r.length;++q){o=r[q];if(!l.has_parameter(o))return[];try{l[o](p[o])}catch(w){console.error(w)}}p=
l.enums().filter(function(t){return r.indexOf(t)===-1});return c.top_transforms({transform:l,given_params:r,needed_params:p,table:a._table}).slice(0,30).filter(function(t){return t.well_defined(a._table)})},n=function(){var l=z(dw.engine.missing_bar),p=[];if(l.length){l=l[l.length-1].col;p.push(dw.fill(a._table[l].name));p.push(dw.fill(a._table[l].name).direction(dw.UP));p.push(dw.filter(dw.is_null(a._table[l].name)))}return p},u=function(){var l=z(dw.engine.valid_bar),p=[];if(l.length){l=l[l.length-
1].col;p.push(dw.filter(dw.is_valid(a._table[l].name)))}return p},x=function(){var l=z(dw.engine.bad_role_bar),p=[];if(l.length){l=l[l.length-1].col;p.push(dw.filter(dw.matches_role(a._table[l].name)))}return p},y=function(){var l=z(dw.engine.bad_type_bar),p=[];if(l.length){l=l[l.length-1].col;p.push(dw.filter(dw.matches_type(a._table[l].name,a._table[l].wrangler_type)))}return p},B=function(){var l=z(dw.engine.row),p=[];if(l.length)p=l=dw.row_inference().candidates(a.table(),l[l.length-1].rows);
return p},F=function(){var l=z(dw.engine.edit),p=[];if(l.length)p=l=dw.edit_inference().candidates(a.table(),l);return p},v=function(){var l=z(dw.engine.col),p=[];if(l.length){l=l[l.length-1].cols.map(function(r){return a._table[r].name});if(l.length>0){p.push({column:l});if(l.length===2){p.push({column:[l[0]],measure:l[1]});p.push({column:[l[1]],measure:l[0]})}}}return p},E=function(l){if((l=l||z(dw.engine.highlight))&&l.length){var p,r,o,q,w,t=a.table();return l.map(function(D){p=D.position.row;
r=D.position.col;o=a._table[r][p];q=D.selection.startCursor;w=D.selection.endCursor;return{type:dw.engine.highlight,params:dw.regex.record(o,q,w,t[r].name,p,t)}})}if((l=z(dw.engine.row))&&l.length)return l.map(function(D){return{type:dw.engine.row,params:{rows:D.rows,table:a.table()}}});if((l=z(dw.engine.col))&&l.length)return l.map(function(D){return{type:dw.engine.col,params:{cols:D.cols,table:a.table()}}})},s=function(){var l=z(dw.engine.highlight),p,r,o,q,w,t,D=a.table();if(!l.length)return[];
t=l.map(function(A){p=A.position.row;r=A.position.col;o=a._table[r][p];q=A.selection.startCursor;w=A.selection.endCursor;return dw.regex.record(o,q,w,D[r].name,p,D)});var G=dw.regex().candidates(t);if(l.length===1||G.length<2)G.unshift({positions:[l[l.length-1].selection.startCursor,l[l.length-1].selection.endCursor]});for(var H=t.length-1;G.length<3&&H>0;){G=dw.regex().candidates(t.slice(t.length-H));H-=1}var M=l[l.length-1].position.col;M=a._table[M].name;G.forEach(function(A){A.column=M});return G=
G.concat(dw.row_inference().candidates(a.table(),t,{type:dw.engine.highlight}))},z=function(l,p){p=p||{};var r=a._inputs,o=r.length-1;for(p=p.clear_types||[l,dw.engine.filter,dw.engine.promote,dw.engine.param];o>=0;){if(p.indexOf(r[o].type)===-1)break;o--}return a._inputs.slice(o+1).filter(function(q){return q.type===l})},C=function(l,p){p=p||{};var r=a._inputs,o=r.length-1;p=p.clear_types||[dw.engine.execute,dw.engine.clear];if(typeOf(l)!="array")l=[l];for(;o>=0;){if(p.indexOf(r[o].type)!=-1)break;
o--}return a._inputs.slice(o+1).filter(function(q){return l.indexOf(q.type)!=-1})};return a};dw.engine.transform_set=[dw.split(),dw.edit(),dw.extract(),dw.cut(),dw.fill(),dw.fold(),dw.merge(),dw.filter(),dw.drop(),dw.unfold(),dw.set_name(),dw.translate(),dw.copy()];dw.engine.highlight="text_select";dw.engine.edit="text_edit";dw.engine.row="row_select";dw.engine.col="col_select";dw.engine.filter="type_select";dw.engine.transform="transform_select";dw.engine.execute="execute_transform";
dw.engine.promote="promote_transform";dw.engine.clear="clear_transform";dw.engine.missing_bar="missing";dw.engine.bad_type_bar="bparse";dw.engine.bad_role_bar="brole";dw.engine.valid_bar="bvalid";dw.engine.param="param_edit";
dw.raw_inference=function(d){for(var a=d.substr(0,1E4),b=a.length,c=d=0,e=0,f=0,g=0,h=0,j=0,i=0;i<b;++i)switch(a[i]){case "\n":d++;break;case ",":c++;break;case '"':e++;break;case "|":j++;break;case "'":f++;break;case "\t":g++;break;case " ":h++;break}a={};b=Math.max(c,g);h=0.8*d;if(b>h){if(c>=h){a.type="csv";a.delimiter=","}else if(g>=h){a.type="tsv";a.delimiter="\t"}else if(j>=h){a.type="pipes";a.delimiter="\\|"}if(f>2*d){a.ignore="single quotes";a.quote_character="'"}else if(e>2*d){a.ignore="double quotes";
a.quote_character='"'}}d=[dw.split("data").on("\n").max(0).result(dw.ROW)];if(a.type){c=dw.split("data").max(0).on(a.delimiter);a.quote_character&&c.quote_character(a.quote_character);d.push(c);a.quote_character&&d.push(dw.cut().on(a.quote_character).max(0))}return{inference:a,transforms:d}};dw=dw||{};
dw.row_inference=function(){var d={};d.candidates=function(g,h,j){j=j||{};var i=j.type||dw.engine.row;j=[];if(h.length)switch(i){case dw.engine.row:i=dw.row(dw.rowIndex(h));j.push({row:i});j.push({keys:h});h.length===1&&j.push({header_row:h[0]});j=j.concat(f(g,h));return j=j.concat(a(g,h));case dw.engine.highlight:h=h.filter(function(k){return k.text.length>0});j=j.concat(b(g,h));j=j.concat(c(g,h));return j=j.concat(e(g,h))}return[]};var a=function(g,h){var j=[];h.length&&g.forEach(function(i){var k=
i[h[h.length-1]];j=k?j.concat([dw.row(dw.eq(i.name,k,true))]):j.concat([dw.row(dw.is_null(i.name))])});j=j.filter(function(i){for(var k=0;k<h.length;++k)if(i.test(g,h[k])===0)return false;return true});return j.map(function(i){return{row:i}})},b=function(g,h){if(h.length>0){g=h[h.length-1];if(g.start===0&&g.end===g.text.length)return[{row:dw.row(dw.eq(g.col,g.text.substr(g.start,g.end),true))}]}return[]},c=function(g,h){if(h.length>0){g=h[h.length-1];if(g.start===0)return[{row:dw.row(dw.starts_with(g.col,
g.text.substr(g.start,g.end),true))}]}return[]},e=function(g,h){if(h.length>0){g=h[h.length-1];return[{row:dw.row(dw.contains(g.col,g.text.substr(g.start,g.end),true))}]}return[]},f=function(g,h){for(var j=dw.row(dw.empty()),i=0;i<h.length;++i)if(!j.test(g,h[i]))return[];return[{row:dw.row(dw.empty())}]};return d};
dw.edit_inference=function(){var d={};d.candidates=function(a,b){var c=[];if(b.length){var e=b[b.length-1],f=a[e.position.col][e.position.row];b=e.val;c.push({column:a[e.position.col].name,to:e.val,row:dw.row(dw.rowIndex([e.position.row]))});var g=a[e.position.col].name;if(f!=undefined)f=""+f;f?c.push({column:g,to:e.val,row:dw.row(dw.eq(g,f,true))}):c.push({column:g,to:e.val,row:dw.row(dw.is_null(g))});f&&b==f.toUpperCase()&&c.push({column:g,update_method:dw.edit.upper});f&&b==f.toLowerCase()&&c.push({column:g,
update_method:dw.edit.lower});if(f&&b.substr(1)==f.substr(1))if(b[0]!=f[0])if(b[0]===f[0].toUpperCase())c.push({column:g,update_method:dw.edit.capitalize});else b[0]===f[0].toLowerCase()&&c.push({column:g,update_method:dw.edit.uncapitalize});if(f===undefined||f.replace(/[ \t\n]/g,"").length===0){f=e.position.col;var h=a[f];e=e.position.row;for(var j=e+1;j<Math.min(e+15,a.rows());++j){var i=h[j];if(i!=undefined&&i!=""){i===b&&c.push(dw.fill(g).direction("up"));break}}for(j=e-1;j>=Math.max(e-15,0);--j){i=
h[j];if(i!=undefined&&i!=""){i===b&&c.push(dw.fill(g).direction("down"));break}}for(j=f-1;j>=Math.max(f-15,0);--j){i=a[j][e];if(i!=undefined&&i!=""){i===b&&c.push(dw.fill().direction("right").row(dw.row(dw.rowIndex([e]))));break}}for(j=f+1;j<Math.min(f+15,a.cols());++j){i=a[j][e];if(i!=undefined&&i!=""){i===b&&c.push(dw.fill(g).direction("left").row(dw.row(dw.rowIndex([e]))));break}}}return c}return[]};return d};
dw.infer_type_transforms=function(d){var a,b=function(c,e){var f=0,g=0,h=0,j=0,i;e=e||c.length;for(var k=0;k<e;++k){i=c[k];if(i===undefined||i.length===0)j++;else{i=""+i;if(!isNaN(Number(i))){f++;Number(i)===parseInt(Number(i))&&g++}if(Date.parse(i)){i=Number(i);if(isNaN(i)||i>1900&&i<2100)h++}}}e=e-j;if(h&&h*2>e)return{type:dw.date(),role:dw.role()};if(g&&g*2>e)return{type:dw.integer(),role:dw.role()};if(f&&f*2>e)return{type:dw.number(),role:dw.role()};f=dw.role();var m=dw.state(),n=0;c.forEach(function(u){m.parse(u)&&
n++});if(n>10||n*2>e)f=m;return{type:dw.string(),role:f}};types_and_roles=d.map(function(c){return b(c)});a=types_and_roles.map(function(c){return c.type});roles=types_and_roles.map(function(c){return c.role});return[dw.set_type(d.map(function(c){return c.name}),a),dw.set_role(d.map(function(c){return c.name}),roles)]};
dw.clause=function(d){d=d||{};var a=d.editor_class,b={},c=jQuery(document.createElement("span"));dv.ivar(b,[{name:"onedit",initial:undefined}]);b.on_edit=function(){};b.draw=function(e,f){f=f||{};editable=f.editable||false;var g=dw.jq("span").append(" "+b.description()+" ");g.attr("title","Edit Parameter");c.append(g);if(!b.plain){c.addClass("editableClause").addClass(a);editable&&g.click(function(){c.empty();var h=b.editor(f);c.append(h);b.on_edit();h.focus()})}b.done_editing=function(h){f.onedit(h)};
e.append(c)};return b};
dw.clause.get=function(d,a){switch(a){case "row":return dw.row_clause(d,d[a](),a);case "column":return dw.column_clause(d,d[a](),a);case "max":return dw.select_clause(d,{select_options:{"0":"repeatedly","1":"once"},param:"max"});case "drop":return dw.select_clause(d,{select_options:{"true":"true","false":"false"},param:"drop"});case "result":return dw.select_clause(d,{select_options:{row:"row",column:"column"},param:"result"});case "direction":return dw.select_clause(d,{select_options:{right:"the left",left:"the right",
up:"below",down:"above"},param:"direction"});case "on":case "before":case "after":case "ignore_between":return dw.regex_clause(d,a);case "quote_character":return dw.select_other(d,a,{});default:return dw.input_clause(d,a)}};
dw.combo_with_other=function(d,a){var b=a.val,c,e=dw.jq("input");e.val(a.val||"").focus();e.blur(function(){a.ondone(e.val())});c=dw.jq("select");d.filter(function(f){return f.value===b}).length||dw.add_select_option(c,b,b);d.forEach(function(f){dw.add_select_option(c,f.name,f.value)});c.change(function(){if(c.attr("value")==="other"){c.replaceWith(e);e.focus()}else a.ondone(c.attr("value"))}).blur(function(){c.attr("value")!="other"&&a.ondone(c.attr("value"))});dw.add_select_option(c,"other");c.val(a.val);
return c};
dw.column_clause=function(d,a,b,c){c=c||{};c.editor_class=c.editor_class||"updatedColumn";var e=c.extra_text||"",f=dw.clause(c),g;f.description=function(){var h=a.slice(0,Math.min(4,a.length)).map(dw.display_name).join(", ");if(a.length>4)h+="...";return h+e};f.editor=function(h){h=h||{};if(h.table){g=dw.jq("select");c.single?g.change(function(){j()}):g.attr("multiple","multiple").css("position","absolute");c.all_columns&&dw.add_select_option(g,"all columns");h.table.forEach(function(i){dw.add_select_option(g,dw.display_name(i.name),
i.name)});var j=function(){var i=g.val()||[];if(i.indexOf("all columns")!=-1)i=[];d=d[b](i);f.done_editing({type:dw.engine.param,value:i,param:c.param,transform:d})};g.val(a.length?a:["all columns"]);g.blur(function(){j()})}else{g=jQuery(document.createElement("input"));g.val(f.description());g.blur(function(){d=d[b](f.value());f.done_editing({type:dw.engine.param,value:g.val(),param:b,transform:d})})}return g};f.value=function(){var h=g.val().replace(/ /g,"").split(/,/g);if(c.clean_val)return h.map(c.clean_val);
return h};return f};dw.input_clause=function(d,a){var b=dw.clause(),c,e=d[a]();b.description=function(){return e};b.editor=function(){c=jQuery(document.createElement("input"));c.val(b.description());c.blur(function(){d=d[a](b.value());b.done_editing({type:dw.engine.param,value:c.val(),param:a,transform:d})});return c};b.value=function(){return c.val()};return b};
dw.key_clause=function(d,a,b,c){c=c||{};c.editor_class=c.editor_class||"updatedColumn";var e=c.extra_text||"",f=dw.clause(c),g;f.description=function(){return a.map(function(h){return h==="header"?h:Number(h)+1}).join(", ")+e};f.editor=function(h){h=h||{};g=jQuery(document.createElement("input"));g.val(f.description());g.blur(function(){d=d[b](f.value());f.done_editing({type:dw.engine.param,value:f.value(),param:b,transform:d})});return g};f.value=function(){var h=g.val().replace(/ /g,"").replace("header",
"-1").split(/,/g).map(function(j){return j==="header"?j:Number(j)-1});if(c.clean_val)return h.map(c.clean_val);return h};return f};
dw.regex_clause=function(d,a,b){b=b||{};b.editor_class=b.editor_class||"updatedColumn";var c=dw.clause(b),e,f=b.value||d[a]();c.description=function(){return dw.regex.friendly_description(f).replace(/^\/|\/$/g,"")};c.editor=function(){e=jQuery(document.createElement("input"));var g=f?f.toString().replace(/^\/|\/$/g,"").replace(/\n/g,"\\n").replace(/\t/g,"\\t"):"";e.val(g);e.blur(function(){c.val();d=d[a](c.val());c.done_editing({type:dw.engine.param,value:c.val(),param:a,transform:d})});return e};
c.editor=function(){var g=f?f.toString().replace(/^\/|\/$/g,"").replace(/\n/g,"\\n").replace(/\t/g,"\\t"):"";return e=dw.combo_with_other([{name:"comma",value:","},{name:"tab",value:"\\t"},{name:"whitespace",value:" "},{name:"newline",value:"\\n"},{name:"pipe",value:"\\|"}],{val:g,ondone:function(h){h=c.val(h);d=d[a](h);c.done_editing({type:dw.engine.param,value:h,param:a,transform:d})}})};c.val=function(g){g=g||e.val();if(g.length!==0)return new RegExp(g.replace(/\\n/g,"\n").replace(/\\t/g,"\t"))};
return c};
dw.row_clause=function(d,a,b,c){c=c||{};c.editor_class=c.editor_class||"droppedRow";b=b||"row";var e=dw.clause(c),f;e.description=function(){if(a!=undefined){var g=a.description();if(typeOf(g)==="array")g=g[0];if(g.length>50){g=g.substr(0,50);g+="..."}return g}else return""};e.editor=function(){f=jQuery(document.createElement("input"));f.val(a?a.formula():"");f.blur(function(){d=d[b](e.val());e.done_editing({type:dw.engine.param,value:f.val(),param:b,transform:d})}).keydown(function(g){f.unbind("blur");if(g.which===
13){d=d[b](e.val());e.done_editing({type:dw.engine.param,value:f.val(),param:b,transform:d})}});return f};e.val=function(){var g=f.val();if(g)return dw.row.fromFormula(g)};return e};
dw.select_clause=function(d,a){var b=dw.clause(),c;a=a||{};var e=a.param,f=a.value||d[e]();b.description=function(){c=jQuery(document.createElement("select"));return a.select_options[f]};b.editor=function(){c=dw.jq("select");dv.keys(a.select_options).forEach(function(g){var h=document.createElement("option");h.value=g;h.text=a.select_options[g];c[0].options.add(h)});c.val(f);c.change(function(){d=d[e](c.attr("value"));b.done_editing({type:dw.engine.param,value:c.attr("value"),param:a.param,transform:d})});
c.blur(function(){d=d[e](c.attr("value"));b.done_editing({type:dw.engine.param,value:c.attr("value"),param:a.param,transform:d})});return c};b.on_edit=function(){};b.value=function(){return c.attr("value")};return b};
dw.select_other=function(d,a,b){b=b||{};b.editor_class=b.editor_class||"updatedColumn";var c=dw.clause(b),e,f=b.value||d[a]();c.description=function(){return f};c.editor=function(){e=jQuery(document.createElement("input"));e.val(f);e.blur(function(){c.val();d=d[a](c.val());c.done_editing({type:dw.engine.param,value:c.val(),param:a,transform:d})});return e};c.editor=function(){return e=dw.combo_with_other([{name:"Quotes",value:'"'},{name:"Single Quotes",value:"'"}],{val:f,ondone:function(g){g=c.val(g);
d=d[a](g);c.done_editing({type:dw.engine.param,value:g,param:a,transform:d})}})};c.val=function(g){g=g||e.val();if(g.length!==0)return g};return c};dw.text_clause=function(d){var a=dw.clause();a.plain=true;a.description=function(){return d};return a};dw.descriptionEditor=function(d,a,b){var c={};c.draw=function(){a.description().forEach(function(e){if(typeOf(e)==="string")e=dw.text_clause(e);e.draw(d,b)})};return c};
dw.detail_editor=function(d,a,b){var c={};ignore=["status","table","which","drop","insert_position","ignore_between","update","method"];a.name==="filter"&&ignore.push("column");a.name!="split"&&ignore.push("result");c.draw=function(){var e,f;a.params().map(function(g){return g.substr(1)}).filter(function(g){return ignore.indexOf(g)===-1}).sort().forEach(function(g){f=dw.jq("div").addClass("detail");var h=dw.jq("div").append(g).addClass("label");f.append(h);e=dw.clause.get(a,g);e.done_editing=function(j){console.log(j);
b.onedit(j)};f.append(e.editor(b).addClass("detail_editor_input"));d.append(f);f.append(dw.jq("div").addClass("clear"))});return d};return c};
dw.editor=function(d,a,b){function c(k){k.addClass("selected");h({transform:f.transform()})}function e(k){k.removeClass("selected")}var f={},g=b.onpromote,h=b.onhighlight,j=b.onselect,i=b.onedit;f.draw=function(){var k,m;editorWrapper=jQuery(document.createElement("div")).attr("id","editorTransformContainer");d.append(editorWrapper);a.forEach(function(n,u){var x=jQuery(document.createElement("div")).addClass("suggestion");u?x.css("opacity",0):x.addClass("firstSuggestion");editorWrapper.append(x);
if(n){k=jQuery(document.createElement("div")).addClass("descriptionEditor");m=jQuery(document.createElement("div")).addClass("editorButton addButton");m.click(function(){j(f.transform())});x.click(function(){u!=0&&f.promote();jQuery(".suggestion").unbind("click")});dw.descriptionEditor(k,n,{onedit:i,editable:u===0,table:b.table}).draw();if(u===0&&n!=null){var y=dw.jq("div").addClass("detail_toggler");x.append(y);y.click(function(){if(n.show_details){B();n.show_details=false}else{F();n.show_details=
true}});var B=function(){x.find(".detail_editor").remove();y.removeClass("detail_expanded")},F=function(){var v=dw.jq("div").addClass("detail_editor");x.append(v);dw.detail_editor(v,n,{onedit:i}).draw();y.addClass("detail_expanded")}}x.append(k);x.append(m);x.append(jQuery(document.createElement("div")).addClass("clear"));x.hoverIntent({over:function(v){var E=f.selected();E.length&&e(E);c(jQuery(v.currentTarget))},timeout:500,out:function(){}});n.show_details&&F()}else x.addClass("emptySuggestion")});
jQuery(".suggestion").filter(":not(.suggestion.selected)").fadeTo(500,1);return f};f.promote=function(){var k=f.selected(),m=k.offset(),n=jQuery(".suggestion:first"),u=n.offset().top-n.height()-35,x=k.width();jQuery(".suggestion").filter(":not(.suggestion.selected)").fadeTo(800,0);setTimeout(function(){k.css("position","absolute").css("top",m.top-k.height()-20).width(x).animate({top:u,width:"+=0"},500,function(){g(f.transform())})},800)};f.prev=function(){var k=f.selected();if(k.length){e(k);c(k.prev())}else c(jQuery(".suggestion:last"))};
f.next=function(){var k=f.selected();if(k.length){e(k);c(k.next())}else c(jQuery(".suggestion:first"))};f.first_suggestion=function(){c(jQuery(".suggestion:nth-child(2)"))};f.working=function(){c(jQuery(".suggestion:first"))};f.first=function(){a[0]?c(jQuery(".suggestion:first")):c(jQuery(".suggestion:nth-child(2)"))};f.transform=function(){return a[f.selected().index()]};f.selected=function(){return jQuery(".suggestion.selected")};return f};
dw.script=function(d,a,b){var c={};c.draw=function(){var e,f,g,h,j,i,k=b.initial||[],m=b.onedit;i=dw.jq("div").addClass("menu").attr("id","scriptBanner");j=dw.jq("span").append("Transform Script").attr("id","scriptTitle");dw.jq("span").append("Import").attr("id","scriptImport").addClass("scriptIO");h=dw.jq("span").append("Export").attr("id","scriptExport").addClass("scriptIO");h.click(b.onexport);d.append(i);i.append(j).append(h);editorWrapper=jQuery(document.createElement("div")).attr("id","scriptTransformContainer");
d.append(editorWrapper);k.concat(a).forEach(function(n){if(!n.deleted()){var u=jQuery(document.createElement("div")).addClass("scriptTransform");u.addClass(n.status());e=jQuery(document.createElement("div")).addClass("descriptionEditor");editorWrapper.append(u);g=jQuery(document.createElement("div"));if(n.active())g.addClass("editorButton annotateButton");else{g.addClass("editorButton deleteButton").attr("title","Delete Transform");g.click(function(){n.delete_transform();b.edit({transform:n,type:"delete"})})}f=
jQuery(document.createElement("div")).addClass("editorButton").addClass("primaryButton");if(n.invalid())f.attr("title",n.errorMessage());else{f.click(function(){n.toggle();b.edit({transform:n,type:n.active()?"redo":"undo"})});n.inactive()?f.attr("title","Redo Transform"):f.attr("title","Undo Transform")}dw.descriptionEditor(e,n,{onedit:m,editable:true}).draw();var x=dw.jq("div").addClass("detail_toggler");u.append(x);u.append(e);u.append(f);u.append(g);u.append(jQuery(document.createElement("div")).addClass("clear"));
x.click(function(){if(n.show_details){y();n.show_details=false}else{B();n.show_details=true}});var y=function(){u.find(".detail_editor").remove();x.removeClass("detail_expanded")},B=function(){var F=dw.jq("div").addClass("detail_editor");u.append(F);dw.detail_editor(F,n,{onedit:m}).draw();x.addClass("detail_expanded")};n.show_details&&B()}});jQuery(".scriptTransform").mouseenter(function(){jQuery(this).addClass("selected")}).mouseleave(function(){jQuery(this).removeClass("selected")});return c};return c};
dw.tmenu=function(d,a){var b={};a=a||{};var c=a.interaction,e=a.transforms||[{name:"Text",sub:[{name:"Split",transform:dw.transform.SPLIT},{name:"Cut",transform:dw.transform.CUT},{name:"Extract",transform:dw.transform.EXTRACT},{name:"Edit",transform:dw.transform.CONVERT}]},{name:"Columns",sub:[{name:"Fill",transform:dw.transform.FILL},{name:"Translate",transform:dw.transform.TRANSLATE},{name:"Drop",transform:dw.transform.DROP},{name:"Merge",transform:dw.transform.MERGE}]},{name:"Rows",sub:[{name:"Delete",
transform:dw.transform.FILTER},{name:"Fill",transform:dw.transform.FILL},{name:"Promote",transform:dw.transform.SET_NAME}]},{name:"Table",sub:[{name:"Fold",transform:dw.transform.FOLD},{name:"Unfold",transform:dw.transform.UNFOLD},{name:"Transpose",transform:dw.transform.TRANSPOSE}]},{name:"Clear",sub:[]}],f=dw.jq("div").addClass("tmenu");d.attr("id","transformMenu");d.append(f);b.draw=function(){var g,h;e.forEach(function(j){g=dw.jq("span");f.append(g);h=dw.jq("p").append(dw.jq("a").append(j.name));
g.append(h);var i=18+18*j.sub.length,k=dw.jq("div").addClass("tsubmenu").height(i);g.append(k);k.hide();j.sub.forEach(function(m){h=dw.jq("p").addClass("submenu").append(dw.jq("a").append(m.name));k.append(h);jQuery(h).click(function(){c({type:dw.engine.filter,transform:m.transform})})});j.name!="Clear"?jQuery(g).click(function(){var m=jQuery(this).position();k.css("left",m.left).css("top",m.top+20);k.show();jQuery(this).height(i);jQuery(this).addClass("openMenu")}).mouseleave(function(){k.hide();
jQuery(this).height(19);jQuery(this).removeClass("openMenu")}):g.addClass("clearMenu").click(function(){a.onclear()})});d.append(dw.jq("div").height(20))};return b};
dw.wrangler=function(d){function a(A){dw.log(A);var J=D.add(A);A.rows=J.rows();A.cols=J.cols();r=p.table(v).input(A).run(13);l=r[0];k();if(A.type===dw.engine.promote)o.working();else A.type===dw.engine.param?o.working():o.first_suggestion()}function b(){dw.infer_type_transforms(v).forEach(function(A){A.sample_apply([v])})}function c(){l=o.transform();i()}function e(){if(!M){M=true;alert("Wrangler only supports up to 40 columns and 1000 rows.  We will preview only the first 40 columns and 1000 rows of data.")}}
function f(A){x(A.transform);dw.log({type:"highlight_suggestion",suggestion:A.transform})}function g(A){A.sample_apply([v]);dw.summary.clear_cache();b();t.add(A);D.clear();a({type:dw.engine.execute,transform:A});u();jQuery("#scriptTransformContainer").scrollTop(1E5)}function h(){D.clear();a({type:dw.engine.clear})}function j(A){D.clear();a({type:dw.engine.promote,transform:A})}function i(){x(l)}function k(){H.empty();dw.tmenu(H,{interaction:a,onclear:h}).draw();o=dw.editor(H,r,{onpromote:j,onhighlight:f,
onselect:g,onedit:a,table:v}).draw()}function m(){var A=dw.jq("select").addClass("exportOptions"),J=jQuery('<form>\t\t<input type="radio" name="exportType" value="data" checked="checked"/> Data<br />\t\t<input type="radio" name="exportType" value="script" /> Script\t\t</form>');J.find(":radio").height(15).width(15).click(function(){A.empty();P()});var P=function(){if(J.find(":radio:checked").val()=="data"){K("csv","Comma-Separated Values (CSV)");K("tsv","Tab-Separated Values (TSV)");K("rowjson","Row-Oriented JSON (One object per row)");
K("columnjson","Column-Oriented JSON (One array per column)");I.attr("value",dw.wrangler_export(v,{}));I.focus();I.select();dw.log({type:"export",params:{type:"csv"}})}else{K("python","Python");K("javascript","JavaScript");I.attr("value",dw.wrangler_export(v,{format:"python",wrangler:t}));I.focus();I.select();dw.log({type:"export",params:{type:"python"}});N.empty();N.append(O)}},K=function(Q,R){dw.add_select_option(A,R,Q)},O="To run python code easy_install datawrangler or download the <a class='runtimeLink' href='http://www.stanford.edu/~skandel/platform/python/DataWrangler-0.1.tar.gz' target='_blank'> python runtime.</a>";
A.change(function(){I.attr("value",dw.wrangler_export(v,{format:A.val(),wrangler:t}));jQuery(".exportHeader").removeClass("selectedExportHeader");jQuery(this).addClass("selectedExportHeader");I.focus();I.select();dw.log({type:"export",params:{type:A.val()}});N.empty();A.val()==="python"&&N.append(O);A.val()==="javascript"&&N.append("To run javascript code, download the <a class='runtimeLink' href='http://www.stanford.edu/~skandel/platform/javascript/dwrt-r0.1.js' target='_blank'> javascript runtime</a>.")});
jQuery("#table").hide();var L=dw.jq("div").attr("id","uploadContainer");L.append(J);L.append(A);var N=dw.jq("div").attr("id","scriptInstructions");jQuery("#profilerCenterPanel").prepend(L);K("csv","Comma-Separated Values (CSV)");K("tsv","Tab-Separated Values (TSV)");K("rowjson","Row-Oriented JSON (One object per row)");K("columnjson","Column-Oriented JSON (One array per column)");L.append(dw.jq("button").attr("id","wranglerInputSubmit").append("Back to Wrangling").click(function(){L.remove();jQuery("#table").show()}));
var I=dw.jq("textArea").attr("id","wranglerInput");L.append(I);I.attr("value",dw.wrangler_export(v,{}));jQuery(".exportHeader:first").addClass("selectedExportHeader");I.focus();I.select();L.append(N);h();dw.log({type:"export",params:{type:"csv"}})}function n(A){s=E.slice();dw.progress_call(t.apply,t,[s]);dw.log({type:"edit_script",params:A});v=s;h();q.draw()}function u(){var A=jQuery("#scriptTransformContainer").scrollTop();G.empty();w=dw.script(G,t,{edit:function(J){n(J)},onexport:m,onedit:n,table:v}).draw();
jQuery("#scriptTransformContainer").scrollTop(A)}function x(A){dw.preview(z,v,A,C,D)}var y=d.tableContainer,B=d.previewContainer,F=d.transformContainer,v=d.table,E=v.slice(),s,z,C,l,p,r,o,q={},w,t=dw.wrangle(),D,G=jQuery(document.createElement("div")).attr("id","scriptContainer"),H=jQuery(document.createElement("div")).attr("id","editorContainer");if(d.initial_transforms){d.initial_transforms.forEach(function(A){t.add(A)});t.apply([v])}F.append(G).append(H);p=dw.engine().table(v);var M=false;z=dw.vtable(y,
{interaction:a,ontablechange:c,onexecute:g,onconfirm:e,wrangler:t});C=dw.vtable(B,{interaction:function(){}});D=dw.table_selection(z);q.draw=function(){r=p.table(v).run();i();k();u()};jQuery(document).bind("keydown",function(A){var J=A&&A.srcElement&&A.srcElement.type;if(J!="text")switch(A.which){case 8:break;case 9:o.promote();J!="textarea"&&A.preventDefault();break;case 38:o.prev();A.preventDefault();break;case 40:o.next();A.preventDefault();break;case 13:l=o.transform();g(l);J!="textarea"&&A.preventDefault();
break;case 27:h();break}});b();q.draw();return q};
